export const acdChildren = {
  general: {
    tagName: "DataAttribute",
    name: "general",
    fc: "ST",
    type: "BOOLEAN",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACD.general.desc",
    mandatory: true,
    presCond: "M",
  },
  dirGeneral: {
    tagName: "DataAttribute",
    name: "dirGeneral",
    fc: "ST",
    type: "FaultDirectionKind",
    typeKind: "ENUMERATED",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACD.dirGeneral.desc",
    mandatory: true,
    presCond: "M",
    children: {
      unknown: {
        tagName: "Literal",
        name: "unknown",
        literalVal: "0",
      },
      forward: {
        tagName: "Literal",
        name: "forward",
        literalVal: "1",
      },
      backward: {
        tagName: "Literal",
        name: "backward",
        literalVal: "2",
      },
      both: {
        tagName: "Literal",
        name: "both",
        literalVal: "3",
      },
    },
  },
  phsA: {
    tagName: "DataAttribute",
    name: "phsA",
    fc: "ST",
    type: "BOOLEAN",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACD.phsA.desc",
    presCond: "AllOrNonePerGroup",
    presCondArgs: "1",
  },
  dirPhsA: {
    tagName: "DataAttribute",
    name: "dirPhsA",
    fc: "ST",
    type: "PhaseFaultDirectionKind",
    typeKind: "ENUMERATED",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACD.dirPhsA.desc",
    presCond: "AllOrNonePerGroup",
    presCondArgs: "1",
    children: {
      unknown: {
        tagName: "Literal",
        name: "unknown",
        literalVal: "0",
      },
      forward: {
        tagName: "Literal",
        name: "forward",
        literalVal: "1",
      },
      backward: {
        tagName: "Literal",
        name: "backward",
        literalVal: "2",
      },
    },
  },
  phsB: {
    tagName: "DataAttribute",
    name: "phsB",
    fc: "ST",
    type: "BOOLEAN",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACD.phsB.desc",
    presCond: "AllOrNonePerGroup",
    presCondArgs: "2",
  },
  dirPhsB: {
    tagName: "DataAttribute",
    name: "dirPhsB",
    fc: "ST",
    type: "PhaseFaultDirectionKind",
    typeKind: "ENUMERATED",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACD.dirPhsB.desc",
    presCond: "AllOrNonePerGroup",
    presCondArgs: "2",
    children: {
      unknown: {
        tagName: "Literal",
        name: "unknown",
        literalVal: "0",
      },
      forward: {
        tagName: "Literal",
        name: "forward",
        literalVal: "1",
      },
      backward: {
        tagName: "Literal",
        name: "backward",
        literalVal: "2",
      },
    },
  },
  phsC: {
    tagName: "DataAttribute",
    name: "phsC",
    fc: "ST",
    type: "BOOLEAN",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACD.phsC.desc",
    presCond: "AllOrNonePerGroup",
    presCondArgs: "3",
  },
  dirPhsC: {
    tagName: "DataAttribute",
    name: "dirPhsC",
    fc: "ST",
    type: "PhaseFaultDirectionKind",
    typeKind: "ENUMERATED",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACD.dirPhsC.desc",
    presCond: "AllOrNonePerGroup",
    presCondArgs: "3",
    children: {
      unknown: {
        tagName: "Literal",
        name: "unknown",
        literalVal: "0",
      },
      forward: {
        tagName: "Literal",
        name: "forward",
        literalVal: "1",
      },
      backward: {
        tagName: "Literal",
        name: "backward",
        literalVal: "2",
      },
    },
  },
  neut: {
    tagName: "DataAttribute",
    name: "neut",
    fc: "ST",
    type: "BOOLEAN",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACD.neut.desc",
    presCond: "AllOrNonePerGroup",
    presCondArgs: "4",
  },
  dirNeut: {
    tagName: "DataAttribute",
    name: "dirNeut",
    fc: "ST",
    type: "PhaseFaultDirectionKind",
    typeKind: "ENUMERATED",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACD.dirNeut.desc",
    presCond: "AllOrNonePerGroup",
    presCondArgs: "4",
    children: {
      unknown: {
        tagName: "Literal",
        name: "unknown",
        literalVal: "0",
      },
      forward: {
        tagName: "Literal",
        name: "forward",
        literalVal: "1",
      },
      backward: {
        tagName: "Literal",
        name: "backward",
        literalVal: "2",
      },
    },
  },
  q: {
    tagName: "DataAttribute",
    name: "q",
    fc: "ST",
    type: "Quality",
    qchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACD.q.desc",
    mandatory: true,
    presCond: "M",
  },
  t: {
    tagName: "DataAttribute",
    name: "t",
    fc: "ST",
    type: "Timestamp",
    descID: "IEC61850_7_3.CDCStatusInfo::ACD.t.desc",
    mandatory: true,
    presCond: "M",
  },
  d: {
    tagName: "DataAttribute",
    name: "d",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
    presCond: "O",
  },
  dU: {
    tagName: "DataAttribute",
    name: "dU",
    fc: "DC",
    type: "Unicode255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
    presCond: "O",
  },
  cdcName: {
    tagName: "DataAttribute",
    name: "cdcName",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
    presCond: "O",
  },
  dataNs: {
    tagName: "DataAttribute",
    name: "dataNs",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
    presCond: "MOdataNs",
  },
};
