export const actChildren = {
  general: {
    tagName: "DataAttribute",
    name: "general",
    fc: "ST",
    type: "BOOLEAN",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACT.general.desc",
    mandatory: true,
    presCond: "M",
  },
  phsA: {
    tagName: "DataAttribute",
    name: "phsA",
    fc: "ST",
    type: "BOOLEAN",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACT.phsA.desc",
    presCond: "O",
  },
  phsB: {
    tagName: "DataAttribute",
    name: "phsB",
    fc: "ST",
    type: "BOOLEAN",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACT.phsB.desc",
    presCond: "O",
  },
  phsC: {
    tagName: "DataAttribute",
    name: "phsC",
    fc: "ST",
    type: "BOOLEAN",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACT.phsC.desc",
    presCond: "O",
  },
  neut: {
    tagName: "DataAttribute",
    name: "neut",
    fc: "ST",
    type: "BOOLEAN",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACT.neut.desc",
    presCond: "O",
  },
  q: {
    tagName: "DataAttribute",
    name: "q",
    fc: "ST",
    type: "Quality",
    qchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::ACT.q.desc",
    mandatory: true,
    presCond: "M",
  },
  t: {
    tagName: "DataAttribute",
    name: "t",
    fc: "ST",
    type: "Timestamp",
    descID: "IEC61850_7_3.CDCStatusInfo::ACT.t.desc",
    mandatory: true,
    presCond: "M",
  },
  originSrc: {
    tagName: "DataAttribute",
    name: "originSrc",
    fc: "ST",
    type: "Originator",
    typeKind: "CONSTRUCTED",
    descID: "IEC61850_7_3.CDCStatusInfo::ACT.originSrc.desc",
    presCond: "O",
    children: {
      orCat: {
        tagName: "SubDataAttribute",
        name: "orCat",
        type: "OriginatorCategoryKind",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_2.DomainTypesGeneral::S_Originator.orCat.desc",
        mandatory: true,
        presCond: "M",
        children: {
          "not-supported": {
            tagName: "Literal",
            name: "not-supported",
            literalVal: "0",
            descID:
              "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.not-supported.desc",
          },
          "bay-control": {
            tagName: "Literal",
            name: "bay-control",
            literalVal: "1",
            descID:
              "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.bay-control.desc",
          },
          "station-control": {
            tagName: "Literal",
            name: "station-control",
            literalVal: "2",
            descID:
              "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.station-control.desc",
          },
          "remote-control": {
            tagName: "Literal",
            name: "remote-control",
            literalVal: "3",
            descID:
              "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.remote-control.desc",
          },
          "automatic-bay": {
            tagName: "Literal",
            name: "automatic-bay",
            literalVal: "4",
            descID:
              "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-bay.desc",
          },
          "automatic-station": {
            tagName: "Literal",
            name: "automatic-station",
            literalVal: "5",
            descID:
              "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-station.desc",
          },
          "automatic-remote": {
            tagName: "Literal",
            name: "automatic-remote",
            literalVal: "6",
            descID:
              "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-remote.desc",
          },
          maintenance: {
            tagName: "Literal",
            name: "maintenance",
            literalVal: "7",
            descID:
              "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.maintenance.desc",
          },
          process: {
            tagName: "Literal",
            name: "process",
            literalVal: "8",
            descID:
              "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.process.desc",
          },
        },
      },
      orIdent: {
        tagName: "SubDataAttribute",
        name: "orIdent",
        type: "Octet64",
        descID: "IEC61850_7_2.DomainTypesGeneral::S_Originator.orIdent.desc",
        mandatory: true,
        presCond: "M",
      },
    },
  },
  operTmPhsA: {
    tagName: "DataAttribute",
    name: "operTmPhsA",
    fc: "ST",
    type: "Timestamp",
    descID: "IEC61850_7_3.CDCStatusInfo::ACT.operTmPhsA.desc",
    presCond: "O",
  },
  operTmPhsB: {
    tagName: "DataAttribute",
    name: "operTmPhsB",
    fc: "ST",
    type: "Timestamp",
    descID: "IEC61850_7_3.CDCStatusInfo::ACT.operTmPhsB.desc",
    presCond: "O",
  },
  operTmPhsC: {
    tagName: "DataAttribute",
    name: "operTmPhsC",
    fc: "ST",
    type: "Timestamp",
    descID: "IEC61850_7_3.CDCStatusInfo::ACT.operTmPhsC.desc",
    presCond: "O",
  },
  d: {
    tagName: "DataAttribute",
    name: "d",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
    presCond: "O",
  },
  dU: {
    tagName: "DataAttribute",
    name: "dU",
    fc: "DC",
    type: "Unicode255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
    presCond: "O",
  },
  cdcName: {
    tagName: "DataAttribute",
    name: "cdcName",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
    presCond: "O",
  },
  dataNs: {
    tagName: "DataAttribute",
    name: "dataNs",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
    presCond: "MOdataNs",
  },
};
