import { apcChildren } from "./APC.js";
import { asgChildren } from "./ASG.js";
import { bacChildren } from "./BAC.js";
import { bscChildren } from "./BSC.js";
import { incChildren } from "./INC.js";
import { ingChildren } from "./ING.js";
import { insChildren } from "./INS.js";
import { iscChildren } from "./ISC.js";
import { lplChildren } from "./LPL.js";
import { mvChildren } from "./MV.js";
import { orgChildren } from "./ORG.js";
import { spcChildren } from "./SPC.js";
import { spsChildren } from "./SPS.js";
import { spgChildren } from "./SPG.js";

export const atcc = {
  Auto: {
    tagName: "DataObject",
    name: "Auto",
    type: "SPC",
    descID: "IEC61850_7_4.AbstractLNsCommon::AutomaticControlLN.Auto.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spcChildren,
  },
  CmdBlk: {
    tagName: "DataObject",
    name: "CmdBlk",
    type: "SPC",
    descID: "IEC61850_7_4.AbstractLNsCommon::ControlledLN.CmdBlk.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spcChildren,
  },
  OpCntRs: {
    tagName: "DataObject",
    name: "OpCntRs",
    type: "INC",
    descID: "IEC61850_7_4.AbstractLNsCommon::ControlledLN.OpCntRs.desc",
    presCond: "O",
    dsPresCond: "O",
    children: incChildren,
  },
  Loc: {
    tagName: "DataObject",
    name: "Loc",
    type: "SPS",
    descID: "IEC61850_7_4.AbstractLNsCommon::ControllingLN.Loc.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spsChildren,
  },
  LocKey: {
    tagName: "DataObject",
    name: "LocKey",
    type: "SPS",
    descID: "IEC61850_7_4.AbstractLNsCommon::ControllingLN.LocKey.desc",
    presCond: "OF",
    presCondArgs: "Loc",
    dsPresCond: "F",
    children: spsChildren,
  },
  LocSta: {
    tagName: "DataObject",
    name: "LocSta",
    type: "SPC",
    descID: "IEC61850_7_4.AbstractLNsCommon::ControllingLN.LocSta.desc",
    presCond: "OF",
    presCondArgs: "Loc",
    dsPresCond: "F",
    children: spcChildren,
  },
  Blk: {
    tagName: "DataObject",
    name: "Blk",
    type: "SPS",
    descID: "IEC61850_7_4.AbstractLNsCommon::FunctionLN.Blk.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spsChildren,
  },
  BlkRef: {
    tagName: "DataObject",
    name: "BlkRef",
    type: "ORG",
    descID: "IEC61850_7_4.AbstractLNsCommon::FunctionLN.BlkRef.desc",
    presCond: "Omulti",
    dsPresCond: "F",
    children: orgChildren,
  },
  ClcExp: {
    tagName: "DataObject",
    name: "ClcExp",
    type: "SPS",
    transient: "true",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcExp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: spsChildren,
  },
  ClcNxtTmms: {
    tagName: "DataObject",
    name: "ClcNxtTmms",
    type: "INS",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcNxtTmms.desc",
    presCond: "O",
    dsPresCond: "O",
    children: insChildren,
  },
  ClcStr: {
    tagName: "DataObject",
    name: "ClcStr",
    type: "SPC",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcStr.desc",
    presCond: "O",
    dsPresCond: "O",
    children: spcChildren,
  },
  ClcMth: {
    tagName: "DataObject",
    name: "ClcMth",
    type: "ENG",
    underlyingType: "CalcMethodKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcMth.desc",
    presCond: "O",
    dsPresCond: "M",
    children: {
      setVal: {
        tagName: "DataAttribute",
        name: "setVal",
        fc: "SE",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.ENG::ENG_SE.setVal.desc",
        mandatory: true,
        presCond: "M",
        type: "CalcMethodKind",
        children: {
          UNSPECIFIED: {
            tagName: "Literal",
            name: "UNSPECIFIED",
            literalVal: "1",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.UNSPECIFIED.desc",
          },
          TRUE_RMS: {
            tagName: "Literal",
            name: "TRUE_RMS",
            literalVal: "2",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.TRUE_RMS.desc",
          },
          PEAK_FUNDAMENTAL: {
            tagName: "Literal",
            name: "PEAK_FUNDAMENTAL",
            literalVal: "3",
            descID:
              "IEC61850_7_4.DOEnums::CalcMethodKind.PEAK_FUNDAMENTAL.desc",
          },
          RMS_FUNDAMENTAL: {
            tagName: "Literal",
            name: "RMS_FUNDAMENTAL",
            literalVal: "4",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.RMS_FUNDAMENTAL.desc",
          },
          MIN: {
            tagName: "Literal",
            name: "MIN",
            literalVal: "5",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.MIN.desc",
          },
          MAX: {
            tagName: "Literal",
            name: "MAX",
            literalVal: "6",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.MAX.desc",
          },
          AVG: {
            tagName: "Literal",
            name: "AVG",
            literalVal: "7",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.AVG.desc",
          },
          SDV: {
            tagName: "Literal",
            name: "SDV",
            literalVal: "8",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.SDV.desc",
          },
          PREDICTION: {
            tagName: "Literal",
            name: "PREDICTION",
            literalVal: "9",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.PREDICTION.desc",
            deprecated: "true",
          },
          RATE: {
            tagName: "Literal",
            name: "RATE",
            literalVal: "10",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.RATE.desc",
            deprecated: "true",
          },
          "P-CLASS": {
            tagName: "Literal",
            name: "P-CLASS",
            literalVal: "11",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.P-CLASS.desc",
          },
          "M-CLASS": {
            tagName: "Literal",
            name: "M-CLASS",
            literalVal: "12",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.M-CLASS.desc",
          },
          DIFF: {
            tagName: "Literal",
            name: "DIFF",
            literalVal: "13",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.DIFF.desc",
          },
        },
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  ClcMod: {
    tagName: "DataObject",
    name: "ClcMod",
    type: "ENG",
    underlyingType: "CalcModeKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcMod.desc",
    presCond: "O",
    dsPresCond: "O",
    children: {
      setVal: {
        tagName: "DataAttribute",
        name: "setVal",
        fc: "SE",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.ENG::ENG_SE.setVal.desc",
        mandatory: true,
        presCond: "M",
        type: "CalcModeKind",
        children: {
          TOTAL: {
            tagName: "Literal",
            name: "TOTAL",
            literalVal: "1",
            descID: "IEC61850_7_4.DOEnums::CalcModeKind.TOTAL.desc",
          },
          PERIOD: {
            tagName: "Literal",
            name: "PERIOD",
            literalVal: "2",
            descID: "IEC61850_7_4.DOEnums::CalcModeKind.PERIOD.desc",
          },
          SLIDING: {
            tagName: "Literal",
            name: "SLIDING",
            literalVal: "3",
            descID: "IEC61850_7_4.DOEnums::CalcModeKind.SLIDING.desc",
          },
        },
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  ClcIntvTyp: {
    tagName: "DataObject",
    name: "ClcIntvTyp",
    type: "ENG",
    underlyingType: "CalcIntervalKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcIntvTyp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: {
      setVal: {
        tagName: "DataAttribute",
        name: "setVal",
        fc: "SE",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.ENG::ENG_SE.setVal.desc",
        mandatory: true,
        presCond: "M",
        type: "CalcIntervalKind",
        children: {
          MS: {
            tagName: "Literal",
            name: "MS",
            literalVal: "1",
          },
          PER_CYCLE: {
            tagName: "Literal",
            name: "PER_CYCLE",
            literalVal: "2",
          },
          CYCLE: {
            tagName: "Literal",
            name: "CYCLE",
            literalVal: "3",
          },
          DAY: {
            tagName: "Literal",
            name: "DAY",
            literalVal: "4",
          },
          WEEK: {
            tagName: "Literal",
            name: "WEEK",
            literalVal: "5",
          },
          MONTH: {
            tagName: "Literal",
            name: "MONTH",
            literalVal: "6",
          },
          YEAR: {
            tagName: "Literal",
            name: "YEAR",
            literalVal: "7",
          },
          EXTERNAL: {
            tagName: "Literal",
            name: "EXTERNAL",
            literalVal: "8",
          },
        },
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  ClcIntvPer: {
    tagName: "DataObject",
    name: "ClcIntvPer",
    type: "ING",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcIntvPer.desc",
    presCond: "O",
    dsPresCond: "O",
    children: ingChildren,
  },
  NumSubIntv: {
    tagName: "DataObject",
    name: "NumSubIntv",
    type: "ING",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.NumSubIntv.desc",
    presCond: "O",
    dsPresCond: "O",
    children: ingChildren,
  },
  ClcRfTyp: {
    tagName: "DataObject",
    name: "ClcRfTyp",
    type: "ENG",
    underlyingType: "CalcIntervalKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcRfTyp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: {
      setVal: {
        tagName: "DataAttribute",
        name: "setVal",
        fc: "SE",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.ENG::ENG_SE.setVal.desc",
        mandatory: true,
        presCond: "M",
        type: "CalcIntervalKind",
        children: {
          MS: {
            tagName: "Literal",
            name: "MS",
            literalVal: "1",
          },
          PER_CYCLE: {
            tagName: "Literal",
            name: "PER_CYCLE",
            literalVal: "2",
          },
          CYCLE: {
            tagName: "Literal",
            name: "CYCLE",
            literalVal: "3",
          },
          DAY: {
            tagName: "Literal",
            name: "DAY",
            literalVal: "4",
          },
          WEEK: {
            tagName: "Literal",
            name: "WEEK",
            literalVal: "5",
          },
          MONTH: {
            tagName: "Literal",
            name: "MONTH",
            literalVal: "6",
          },
          YEAR: {
            tagName: "Literal",
            name: "YEAR",
            literalVal: "7",
          },
          EXTERNAL: {
            tagName: "Literal",
            name: "EXTERNAL",
            literalVal: "8",
          },
        },
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  ClcRfPer: {
    tagName: "DataObject",
    name: "ClcRfPer",
    type: "ING",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcRfPer.desc",
    presCond: "O",
    dsPresCond: "O",
    children: ingChildren,
  },
  ClcSrc: {
    tagName: "DataObject",
    name: "ClcSrc",
    type: "ORG",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcSrc.desc",
    presCond: "F",
    dsPresCond: "M",
    children: orgChildren,
  },
  InSyn: {
    tagName: "DataObject",
    name: "InSyn",
    type: "ORG",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.InSyn.desc",
    presCond: "O",
    dsPresCond: "O",
    children: orgChildren,
  },
  NamPlt: {
    tagName: "DataObject",
    name: "NamPlt",
    type: "LPL",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.NamPlt.desc",
    presCond: "MONamPlt",
    presCondArgsID:
      "IEC61850_7_4.AbstractLNsCommon::DomainLN__(_MONamPlt_=__((_NamPlt_))__)_.cond.AbstractLNsCommon::DomainLN.NamPlt",
    dsPresCond: "MONamPlt",
    dsPresCondArgsID:
      "IEC61850_7_4.AbstractLNsCommon::DomainLN__(_MONamPlt_=__((_NamPlt_))__)_.dsCond.AbstractLNsCommon::DomainLN.NamPlt",
    children: lplChildren,
  },
  Beh: {
    tagName: "DataObject",
    name: "Beh",
    type: "ENS",
    underlyingType: "BehaviourModeKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.Beh.desc",
    mandatory: true,
    presCond: "M",
    dsPresCond: "M",
    children: {
      stVal: {
        tagName: "DataAttribute",
        name: "stVal",
        fc: "ST",
        typeKind: "ENUMERATED",
        dchg: "true",
        dupd: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.stVal.desc",
        mandatory: true,
        presCond: "M",
        type: "BehaviourModeKind",
        children: {
          on: {
            tagName: "Literal",
            name: "on",
            literalVal: "1",
          },
          blocked: {
            tagName: "Literal",
            name: "blocked",
            literalVal: "2",
          },
          test: {
            tagName: "Literal",
            name: "test",
            literalVal: "3",
          },
          "test/blocked": {
            tagName: "Literal",
            name: "test/blocked",
            literalVal: "4",
          },
          off: {
            tagName: "Literal",
            name: "off",
            literalVal: "5",
          },
        },
      },
      q: {
        tagName: "DataAttribute",
        name: "q",
        fc: "ST",
        type: "Quality",
        qchg: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.q.desc",
        mandatory: true,
        presCond: "M",
      },
      t: {
        tagName: "DataAttribute",
        name: "t",
        fc: "ST",
        type: "Timestamp",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.t.desc",
        mandatory: true,
        presCond: "M",
      },
      subEna: {
        tagName: "DataAttribute",
        name: "subEna",
        fc: "SV",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subEna.desc",
        presCond: "MFsubst",
      },
      subVal: {
        tagName: "DataAttribute",
        name: "subVal",
        fc: "SV",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.subVal.desc",
        presCond: "MFsubst",
        type: "BehaviourModeKind",
        children: {
          on: {
            tagName: "Literal",
            name: "on",
            literalVal: "1",
          },
          blocked: {
            tagName: "Literal",
            name: "blocked",
            literalVal: "2",
          },
          test: {
            tagName: "Literal",
            name: "test",
            literalVal: "3",
          },
          "test/blocked": {
            tagName: "Literal",
            name: "test/blocked",
            literalVal: "4",
          },
          off: {
            tagName: "Literal",
            name: "off",
            literalVal: "5",
          },
        },
      },
      subQ: {
        tagName: "DataAttribute",
        name: "subQ",
        fc: "SV",
        type: "Quality",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subQ.desc",
        presCond: "MFsubst",
      },
      subID: {
        tagName: "DataAttribute",
        name: "subID",
        fc: "SV",
        type: "VisString64",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subID.desc",
        presCond: "MFsubst",
      },
      blkEna: {
        tagName: "DataAttribute",
        name: "blkEna",
        fc: "BL",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.blkEna.desc",
        presCond: "O",
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  Health: {
    tagName: "DataObject",
    name: "Health",
    type: "ENS",
    underlyingType: "HealthKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.Health.desc",
    presCond: "O",
    dsPresCond: "O",
    children: {
      stVal: {
        tagName: "DataAttribute",
        name: "stVal",
        fc: "ST",
        typeKind: "ENUMERATED",
        dchg: "true",
        dupd: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.stVal.desc",
        mandatory: true,
        presCond: "M",
        type: "HealthKind",
        children: {
          Ok: {
            tagName: "Literal",
            name: "Ok",
            literalVal: "1",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Ok.desc",
          },
          Warning: {
            tagName: "Literal",
            name: "Warning",
            literalVal: "2",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Warning.desc",
          },
          Alarm: {
            tagName: "Literal",
            name: "Alarm",
            literalVal: "3",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Alarm.desc",
          },
        },
      },
      q: {
        tagName: "DataAttribute",
        name: "q",
        fc: "ST",
        type: "Quality",
        qchg: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.q.desc",
        mandatory: true,
        presCond: "M",
      },
      t: {
        tagName: "DataAttribute",
        name: "t",
        fc: "ST",
        type: "Timestamp",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.t.desc",
        mandatory: true,
        presCond: "M",
      },
      subEna: {
        tagName: "DataAttribute",
        name: "subEna",
        fc: "SV",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subEna.desc",
        presCond: "MFsubst",
      },
      subVal: {
        tagName: "DataAttribute",
        name: "subVal",
        fc: "SV",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.subVal.desc",
        presCond: "MFsubst",
        type: "HealthKind",
        children: {
          Ok: {
            tagName: "Literal",
            name: "Ok",
            literalVal: "1",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Ok.desc",
          },
          Warning: {
            tagName: "Literal",
            name: "Warning",
            literalVal: "2",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Warning.desc",
          },
          Alarm: {
            tagName: "Literal",
            name: "Alarm",
            literalVal: "3",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Alarm.desc",
          },
        },
      },
      subQ: {
        tagName: "DataAttribute",
        name: "subQ",
        fc: "SV",
        type: "Quality",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subQ.desc",
        presCond: "MFsubst",
      },
      subID: {
        tagName: "DataAttribute",
        name: "subID",
        fc: "SV",
        type: "VisString64",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subID.desc",
        presCond: "MFsubst",
      },
      blkEna: {
        tagName: "DataAttribute",
        name: "blkEna",
        fc: "BL",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.blkEna.desc",
        presCond: "O",
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  Mir: {
    tagName: "DataObject",
    name: "Mir",
    type: "SPS",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.Mir.desc",
    presCond: "MOcond",
    presCondArgs: "1",
    presCondArgsID:
      "IEC61850_7_4.AbstractLNsCommon::DomainLN__(_MOcond(1)_=__((_Mir_))__)_.cond.AbstractLNsCommon::DomainLN.Mir",
    dsPresCond: "MOcond",
    dsPresCondArgs: "1",
    dsPresCondArgsID:
      "IEC61850_7_4.AbstractLNsCommon::DomainLN__(_MOcond(1)_=__((_Mir_))__)_.dsCond.AbstractLNsCommon::DomainLN.Mir",
    children: spsChildren,
  },
  Mod: {
    tagName: "DataObject",
    name: "Mod",
    type: "ENC",
    underlyingType: "BehaviourModeKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.Mod.desc",
    presCond: "O",
    dsPresCond: "O",
    children: {
      origin: {
        tagName: "DataAttribute",
        name: "origin",
        fc: "ST",
        type: "Originator",
        typeKind: "CONSTRUCTED",
        descID: "IEC61850_7_3.CDCControl::ENC.origin.desc",
        presCond: "O",
        children: {
          orCat: {
            tagName: "SubDataAttribute",
            name: "orCat",
            type: "OriginatorCategoryKind",
            typeKind: "ENUMERATED",
            descID: "IEC61850_7_2.DomainTypesGeneral::S_Originator.orCat.desc",
            mandatory: true,
            presCond: "M",
            children: {
              "not-supported": {
                tagName: "Literal",
                name: "not-supported",
                literalVal: "0",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.not-supported.desc",
              },
              "bay-control": {
                tagName: "Literal",
                name: "bay-control",
                literalVal: "1",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.bay-control.desc",
              },
              "station-control": {
                tagName: "Literal",
                name: "station-control",
                literalVal: "2",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.station-control.desc",
              },
              "remote-control": {
                tagName: "Literal",
                name: "remote-control",
                literalVal: "3",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.remote-control.desc",
              },
              "automatic-bay": {
                tagName: "Literal",
                name: "automatic-bay",
                literalVal: "4",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-bay.desc",
              },
              "automatic-station": {
                tagName: "Literal",
                name: "automatic-station",
                literalVal: "5",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-station.desc",
              },
              "automatic-remote": {
                tagName: "Literal",
                name: "automatic-remote",
                literalVal: "6",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-remote.desc",
              },
              maintenance: {
                tagName: "Literal",
                name: "maintenance",
                literalVal: "7",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.maintenance.desc",
              },
              process: {
                tagName: "Literal",
                name: "process",
                literalVal: "8",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.process.desc",
              },
            },
          },
          orIdent: {
            tagName: "SubDataAttribute",
            name: "orIdent",
            type: "Octet64",
            descID:
              "IEC61850_7_2.DomainTypesGeneral::S_Originator.orIdent.desc",
            mandatory: true,
            presCond: "M",
          },
        },
      },
      ctlNum: {
        tagName: "DataAttribute",
        name: "ctlNum",
        fc: "ST",
        type: "INT8U",
        descID: "IEC61850_7_3.CDCControl::ENC.ctlNum.desc",
        presCond: "O",
      },
      stVal: {
        tagName: "DataAttribute",
        name: "stVal",
        fc: "ST",
        typeKind: "ENUMERATED",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.stVal.desc",
        mandatory: true,
        presCond: "M",
        type: "BehaviourModeKind",
        children: {
          on: {
            tagName: "Literal",
            name: "on",
            literalVal: "1",
          },
          blocked: {
            tagName: "Literal",
            name: "blocked",
            literalVal: "2",
          },
          test: {
            tagName: "Literal",
            name: "test",
            literalVal: "3",
          },
          "test/blocked": {
            tagName: "Literal",
            name: "test/blocked",
            literalVal: "4",
          },
          off: {
            tagName: "Literal",
            name: "off",
            literalVal: "5",
          },
        },
      },
      q: {
        tagName: "DataAttribute",
        name: "q",
        fc: "ST",
        type: "Quality",
        qchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.q.desc",
        mandatory: true,
        presCond: "M",
      },
      t: {
        tagName: "DataAttribute",
        name: "t",
        fc: "ST",
        type: "Timestamp",
        descID: "IEC61850_7_3.CDCControl::ENC.t.desc",
        mandatory: true,
        presCond: "M",
      },
      stSeld: {
        tagName: "DataAttribute",
        name: "stSeld",
        fc: "ST",
        type: "BOOLEAN",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.stSeld.desc",
        presCond: "MOsbo",
      },
      opRcvd: {
        tagName: "DataAttribute",
        name: "opRcvd",
        fc: "OR",
        type: "BOOLEAN",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ControlTestingCDC.opRcvd.desc",
        presCond: "O",
      },
      opOk: {
        tagName: "DataAttribute",
        name: "opOk",
        fc: "OR",
        type: "BOOLEAN",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ControlTestingCDC.opOk.desc",
        presCond: "O",
      },
      tOpOk: {
        tagName: "DataAttribute",
        name: "tOpOk",
        fc: "OR",
        type: "Timestamp",
        descID: "IEC61850_7_3.CDCControl::ControlTestingCDC.tOpOk.desc",
        presCond: "O",
      },
      subEna: {
        tagName: "DataAttribute",
        name: "subEna",
        fc: "SV",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subEna.desc",
        presCond: "MFsubst",
      },
      subVal: {
        tagName: "DataAttribute",
        name: "subVal",
        fc: "SV",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.CDCControl::ENC.subVal.desc",
        presCond: "MFsubst",
        type: "BehaviourModeKind",
        children: {
          on: {
            tagName: "Literal",
            name: "on",
            literalVal: "1",
          },
          blocked: {
            tagName: "Literal",
            name: "blocked",
            literalVal: "2",
          },
          test: {
            tagName: "Literal",
            name: "test",
            literalVal: "3",
          },
          "test/blocked": {
            tagName: "Literal",
            name: "test/blocked",
            literalVal: "4",
          },
          off: {
            tagName: "Literal",
            name: "off",
            literalVal: "5",
          },
        },
      },
      subQ: {
        tagName: "DataAttribute",
        name: "subQ",
        fc: "SV",
        type: "Quality",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subQ.desc",
        presCond: "MFsubst",
      },
      subID: {
        tagName: "DataAttribute",
        name: "subID",
        fc: "SV",
        type: "VisString64",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subID.desc",
        presCond: "MFsubst",
      },
      blkEna: {
        tagName: "DataAttribute",
        name: "blkEna",
        fc: "BL",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.blkEna.desc",
        presCond: "O",
      },
      ctlModel: {
        tagName: "DataAttribute",
        name: "ctlModel",
        fc: "CF",
        type: "CtlModelKind",
        typeKind: "ENUMERATED",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.ctlModel.desc",
        mandatory: true,
        presCond: "M",
        children: {
          "status-only": {
            tagName: "Literal",
            name: "status-only",
            literalVal: "0",
            descID: "IEC61850_7_3.DAEnums::CtlModelKind.status-only.desc",
          },
          "direct-with-normal-security": {
            tagName: "Literal",
            name: "direct-with-normal-security",
            literalVal: "1",
            descID:
              "IEC61850_7_3.DAEnums::CtlModelKind.direct-with-normal-security.desc",
          },
          "sbo-with-normal-security": {
            tagName: "Literal",
            name: "sbo-with-normal-security",
            literalVal: "2",
            descID:
              "IEC61850_7_3.DAEnums::CtlModelKind.sbo-with-normal-security.desc",
          },
          "direct-with-enhanced-security": {
            tagName: "Literal",
            name: "direct-with-enhanced-security",
            literalVal: "3",
            descID:
              "IEC61850_7_3.DAEnums::CtlModelKind.direct-with-enhanced-security.desc",
          },
          "sbo-with-enhanced-security": {
            tagName: "Literal",
            name: "sbo-with-enhanced-security",
            literalVal: "4",
            descID:
              "IEC61850_7_3.DAEnums::CtlModelKind.sbo-with-enhanced-security.desc",
          },
        },
      },
      sboTimeout: {
        tagName: "DataAttribute",
        name: "sboTimeout",
        fc: "CF",
        type: "INT32U",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.sboTimeout.desc",
        presCond: "MOsbo",
      },
      sboClass: {
        tagName: "DataAttribute",
        name: "sboClass",
        fc: "CF",
        type: "SboClassKind",
        typeKind: "ENUMERATED",
        defaultValue: "operate-once",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.sboClass.desc",
        presCond: "O",
        children: {
          "operate-once": {
            tagName: "Literal",
            name: "operate-once",
            literalVal: "0",
            descID: "IEC61850_7_3.DAEnums::SboClassKind.operate-once.desc",
          },
          "operate-many": {
            tagName: "Literal",
            name: "operate-many",
            literalVal: "1",
            descID: "IEC61850_7_3.DAEnums::SboClassKind.operate-many.desc",
          },
        },
      },
      operTimeout: {
        tagName: "DataAttribute",
        name: "operTimeout",
        fc: "CF",
        type: "INT32U",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.operTimeout.desc",
        presCond: "MOenhanced",
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
      SBO: {
        tagName: "ServiceDataAttribute",
        name: "SBO",
        typeKind: "BASIC",
        type: "VisString129",
        fc: "CO",
        presCond: "MOsboNormal",
        descID: "IEC 61850-8-1:2003.SBO",
      },
      SBOw: {
        tagName: "ServiceDataAttribute",
        name: "SBOw",
        typeKind: "CONSTRUCTED",
        type: "SBOw",
        underlyingTypeKind: "ENUMERATED",
        fc: "CO",
        presCond: "MOsboEnhanced",
        children: {
          ctlVal: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlVal",
            name: "ctlVal",
            typeKind: "undefined",
            mandatory: true,
            presCond: "M",
          },
          operTm: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.operTm",
            name: "operTm",
            typeKind: "BASIC",
            type: "Timestamp",
            presCond: "MOoperTm",
          },
          origin: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.origin",
            name: "origin",
            typeKind: "CONSTRUCTED",
            type: "Originator",
            mandatory: true,
            presCond: "M",
            children: {
              orCat: {
                tagName: "SubDataAttribute",
                name: "orCat",
                type: "OriginatorCategoryKind",
                typeKind: "ENUMERATED",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orCat.desc",
                mandatory: true,
                presCond: "M",
                children: {
                  "not-supported": {
                    tagName: "Literal",
                    name: "not-supported",
                    literalVal: "0",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.not-supported.desc",
                  },
                  "bay-control": {
                    tagName: "Literal",
                    name: "bay-control",
                    literalVal: "1",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.bay-control.desc",
                  },
                  "station-control": {
                    tagName: "Literal",
                    name: "station-control",
                    literalVal: "2",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.station-control.desc",
                  },
                  "remote-control": {
                    tagName: "Literal",
                    name: "remote-control",
                    literalVal: "3",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.remote-control.desc",
                  },
                  "automatic-bay": {
                    tagName: "Literal",
                    name: "automatic-bay",
                    literalVal: "4",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-bay.desc",
                  },
                  "automatic-station": {
                    tagName: "Literal",
                    name: "automatic-station",
                    literalVal: "5",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-station.desc",
                  },
                  "automatic-remote": {
                    tagName: "Literal",
                    name: "automatic-remote",
                    literalVal: "6",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-remote.desc",
                  },
                  maintenance: {
                    tagName: "Literal",
                    name: "maintenance",
                    literalVal: "7",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.maintenance.desc",
                  },
                  process: {
                    tagName: "Literal",
                    name: "process",
                    literalVal: "8",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.process.desc",
                  },
                },
              },
              orIdent: {
                tagName: "SubDataAttribute",
                name: "orIdent",
                type: "Octet64",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orIdent.desc",
                mandatory: true,
                presCond: "M",
              },
            },
          },
          ctlNum: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlNum",
            name: "ctlNum",
            typeKind: "BASIC",
            type: "INT8U",
            mandatory: true,
            presCond: "M",
          },
          T: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.T",
            name: "T",
            typeKind: "BASIC",
            type: "Timestamp",
            mandatory: true,
            presCond: "M",
          },
          Test: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.Test",
            name: "Test",
            typeKind: "BASIC",
            type: "BOOLEAN",
            mandatory: true,
            presCond: "M",
          },
          Check: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.Check",
            name: "Check",
            typeKind: "BASIC",
            type: "Check",
            mandatory: true,
            presCond: "M",
          },
        },
      },
      Oper: {
        tagName: "ServiceDataAttribute",
        name: "Oper",
        typeKind: "CONSTRUCTED",
        type: "Oper",
        underlyingTypeKind: "ENUMERATED",
        fc: "CO",
        presCond: "MOctrl",
        children: {
          ctlVal: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlVal",
            name: "ctlVal",
            typeKind: "undefined",
            mandatory: true,
            presCond: "M",
          },
          operTm: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.operTm",
            name: "operTm",
            typeKind: "BASIC",
            type: "Timestamp",
            presCond: "MOoperTm",
          },
          origin: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.origin",
            name: "origin",
            typeKind: "CONSTRUCTED",
            type: "Originator",
            mandatory: true,
            presCond: "M",
            children: {
              orCat: {
                tagName: "SubDataAttribute",
                name: "orCat",
                type: "OriginatorCategoryKind",
                typeKind: "ENUMERATED",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orCat.desc",
                mandatory: true,
                presCond: "M",
                children: {
                  "not-supported": {
                    tagName: "Literal",
                    name: "not-supported",
                    literalVal: "0",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.not-supported.desc",
                  },
                  "bay-control": {
                    tagName: "Literal",
                    name: "bay-control",
                    literalVal: "1",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.bay-control.desc",
                  },
                  "station-control": {
                    tagName: "Literal",
                    name: "station-control",
                    literalVal: "2",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.station-control.desc",
                  },
                  "remote-control": {
                    tagName: "Literal",
                    name: "remote-control",
                    literalVal: "3",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.remote-control.desc",
                  },
                  "automatic-bay": {
                    tagName: "Literal",
                    name: "automatic-bay",
                    literalVal: "4",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-bay.desc",
                  },
                  "automatic-station": {
                    tagName: "Literal",
                    name: "automatic-station",
                    literalVal: "5",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-station.desc",
                  },
                  "automatic-remote": {
                    tagName: "Literal",
                    name: "automatic-remote",
                    literalVal: "6",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-remote.desc",
                  },
                  maintenance: {
                    tagName: "Literal",
                    name: "maintenance",
                    literalVal: "7",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.maintenance.desc",
                  },
                  process: {
                    tagName: "Literal",
                    name: "process",
                    literalVal: "8",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.process.desc",
                  },
                },
              },
              orIdent: {
                tagName: "SubDataAttribute",
                name: "orIdent",
                type: "Octet64",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orIdent.desc",
                mandatory: true,
                presCond: "M",
              },
            },
          },
          ctlNum: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlNum",
            name: "ctlNum",
            typeKind: "BASIC",
            type: "INT8U",
            mandatory: true,
            presCond: "M",
          },
          T: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.T",
            name: "T",
            typeKind: "BASIC",
            type: "Timestamp",
            mandatory: true,
            presCond: "M",
          },
          Test: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.Test",
            name: "Test",
            typeKind: "BASIC",
            type: "BOOLEAN",
            mandatory: true,
            presCond: "M",
          },
          Check: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.Check",
            name: "Check",
            typeKind: "BASIC",
            type: "Check",
            mandatory: true,
            presCond: "M",
          },
        },
      },
      Cancel: {
        tagName: "ServiceDataAttribute",
        name: "Cancel",
        typeKind: "CONSTRUCTED",
        type: "Cancel",
        underlyingTypeKind: "ENUMERATED",
        fc: "CO",
        presCond: "MOsbo",
        children: {
          ctlVal: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlVal",
            name: "ctlVal",
            typeKind: "undefined",
            mandatory: true,
            presCond: "M",
          },
          operTm: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.operTm",
            name: "operTm",
            typeKind: "BASIC",
            type: "Timestamp",
            presCond: "MOoperTm",
          },
          origin: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.origin",
            name: "origin",
            typeKind: "CONSTRUCTED",
            type: "Originator",
            mandatory: true,
            presCond: "M",
            children: {
              orCat: {
                tagName: "SubDataAttribute",
                name: "orCat",
                type: "OriginatorCategoryKind",
                typeKind: "ENUMERATED",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orCat.desc",
                mandatory: true,
                presCond: "M",
                children: {
                  "not-supported": {
                    tagName: "Literal",
                    name: "not-supported",
                    literalVal: "0",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.not-supported.desc",
                  },
                  "bay-control": {
                    tagName: "Literal",
                    name: "bay-control",
                    literalVal: "1",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.bay-control.desc",
                  },
                  "station-control": {
                    tagName: "Literal",
                    name: "station-control",
                    literalVal: "2",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.station-control.desc",
                  },
                  "remote-control": {
                    tagName: "Literal",
                    name: "remote-control",
                    literalVal: "3",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.remote-control.desc",
                  },
                  "automatic-bay": {
                    tagName: "Literal",
                    name: "automatic-bay",
                    literalVal: "4",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-bay.desc",
                  },
                  "automatic-station": {
                    tagName: "Literal",
                    name: "automatic-station",
                    literalVal: "5",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-station.desc",
                  },
                  "automatic-remote": {
                    tagName: "Literal",
                    name: "automatic-remote",
                    literalVal: "6",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-remote.desc",
                  },
                  maintenance: {
                    tagName: "Literal",
                    name: "maintenance",
                    literalVal: "7",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.maintenance.desc",
                  },
                  process: {
                    tagName: "Literal",
                    name: "process",
                    literalVal: "8",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.process.desc",
                  },
                },
              },
              orIdent: {
                tagName: "SubDataAttribute",
                name: "orIdent",
                type: "Octet64",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orIdent.desc",
                mandatory: true,
                presCond: "M",
              },
            },
          },
          ctlNum: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlNum",
            name: "ctlNum",
            typeKind: "BASIC",
            type: "INT8U",
            mandatory: true,
            presCond: "M",
          },
          T: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.T",
            name: "T",
            typeKind: "BASIC",
            type: "Timestamp",
            mandatory: true,
            presCond: "M",
          },
          Test: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.Test",
            name: "Test",
            typeKind: "BASIC",
            type: "BOOLEAN",
            mandatory: true,
            presCond: "M",
          },
        },
      },
    },
  },
  InRef: {
    tagName: "DataObject",
    name: "InRef",
    type: "ORG",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.InRef.desc",
    presCond: "Omulti",
    dsPresCond: "Omulti",
    children: orgChildren,
  },
  HiTapPos: {
    tagName: "DataObject",
    name: "HiTapPos",
    type: "INS",
    descID: "IEC61850_7_4.LNGroupA::ATCC.HiTapPos.desc",
    presCond: "O",
    dsPresCond: "O",
    children: insChildren,
  },
  LoTapPos: {
    tagName: "DataObject",
    name: "LoTapPos",
    type: "INS",
    descID: "IEC61850_7_4.LNGroupA::ATCC.LoTapPos.desc",
    presCond: "O",
    dsPresCond: "O",
    children: insChildren,
  },
  TapOpR: {
    tagName: "DataObject",
    name: "TapOpR",
    type: "SPS",
    transient: "true",
    descID: "IEC61850_7_4.LNGroupA::ATCC.TapOpR.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spsChildren,
  },
  TapOpL: {
    tagName: "DataObject",
    name: "TapOpL",
    type: "SPS",
    transient: "true",
    descID: "IEC61850_7_4.LNGroupA::ATCC.TapOpL.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spsChildren,
  },
  TapOpStop: {
    tagName: "DataObject",
    name: "TapOpStop",
    type: "SPS",
    transient: "true",
    descID: "IEC61850_7_4.LNGroupA::ATCC.TapOpStop.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spsChildren,
  },
  TapOpErr: {
    tagName: "DataObject",
    name: "TapOpErr",
    type: "SPS",
    descID: "IEC61850_7_4.LNGroupA::ATCC.TapOpErr.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spsChildren,
  },
  LTCBlkVLo: {
    tagName: "DataObject",
    name: "LTCBlkVLo",
    type: "SPS",
    descID: "IEC61850_7_4.LNGroupA::ATCC.LTCBlkVLo.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spsChildren,
  },
  LTCBlkVHi: {
    tagName: "DataObject",
    name: "LTCBlkVHi",
    type: "SPS",
    descID: "IEC61850_7_4.LNGroupA::ATCC.LTCBlkVHi.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spsChildren,
  },
  LTCBlkAHi: {
    tagName: "DataObject",
    name: "LTCBlkAHi",
    type: "SPS",
    descID: "IEC61850_7_4.LNGroupA::ATCC.LTCBlkAHi.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spsChildren,
  },
  EndPosR: {
    tagName: "DataObject",
    name: "EndPosR",
    type: "SPS",
    descID: "IEC61850_7_4.LNGroupA::ATCC.EndPosR.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spsChildren,
  },
  EndPosL: {
    tagName: "DataObject",
    name: "EndPosL",
    type: "SPS",
    descID: "IEC61850_7_4.LNGroupA::ATCC.EndPosL.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spsChildren,
  },
  ErrPar: {
    tagName: "DataObject",
    name: "ErrPar",
    type: "SPS",
    descID: "IEC61850_7_4.LNGroupA::ATCC.ErrPar.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spsChildren,
  },
  CtlV: {
    tagName: "DataObject",
    name: "CtlV",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupA::ATCC.CtlV.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  LodA: {
    tagName: "DataObject",
    name: "LodA",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupA::ATCC.LodA.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  CircA: {
    tagName: "DataObject",
    name: "CircA",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupA::ATCC.CircA.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  PhAng: {
    tagName: "DataObject",
    name: "PhAng",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupA::ATCC.PhAng.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  HiCtlV: {
    tagName: "DataObject",
    name: "HiCtlV",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupA::ATCC.HiCtlV.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  LoCtlV: {
    tagName: "DataObject",
    name: "LoCtlV",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupA::ATCC.LoCtlV.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  HiDmdA: {
    tagName: "DataObject",
    name: "HiDmdA",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupA::ATCC.HiDmdA.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  TapChg: {
    tagName: "DataObject",
    name: "TapChg",
    type: "BSC",
    descID: "IEC61850_7_4.LNGroupA::ATCC.TapChg.desc",
    presCond: "AtLeastOne",
    presCondArgs: "1",
    dsPresCond: "O",
    children: bscChildren,
  },
  TapPos: {
    tagName: "DataObject",
    name: "TapPos",
    type: "ISC",
    descID: "IEC61850_7_4.LNGroupA::ATCC.TapPos.desc",
    presCond: "AtLeastOne",
    presCondArgs: "1",
    dsPresCond: "O",
    children: iscChildren,
  },
  VolSpt: {
    tagName: "DataObject",
    name: "VolSpt",
    type: "APC",
    descID: "IEC61850_7_4.LNGroupA::ATCC.VolSpt.desc",
    presCond: "AtLeastOne",
    presCondArgs: "2",
    dsPresCond: "O",
    children: apcChildren,
  },
  BndCtrChg: {
    tagName: "DataObject",
    name: "BndCtrChg",
    type: "BAC",
    descID: "IEC61850_7_4.LNGroupA::ATCC.BndCtrChg.desc",
    presCond: "AtLeastOne",
    presCondArgs: "2",
    dsPresCond: "O",
    children: bacChildren,
  },
  ParOp: {
    tagName: "DataObject",
    name: "ParOp",
    type: "SPC",
    descID: "IEC61850_7_4.LNGroupA::ATCC.ParOp.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spcChildren,
  },
  LTCBlk: {
    tagName: "DataObject",
    name: "LTCBlk",
    type: "SPC",
    descID: "IEC61850_7_4.LNGroupA::ATCC.LTCBlk.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spcChildren,
  },
  LTCDragRs: {
    tagName: "DataObject",
    name: "LTCDragRs",
    type: "SPC",
    transient: "true",
    descID: "IEC61850_7_4.LNGroupA::ATCC.LTCDragRs.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spcChildren,
  },
  VRed: {
    tagName: "DataObject",
    name: "VRed",
    type: "SPC",
    descID: "IEC61850_7_4.LNGroupA::ATCC.VRed.desc",
    deprecated: "true",
    presCond: "Omulti",
    dsPresCond: "F",
    children: spcChildren,
  },
  BndCtr: {
    tagName: "DataObject",
    name: "BndCtr",
    type: "ASG",
    descID: "IEC61850_7_4.LNGroupA::ATCC.BndCtr.desc",
    presCond: "AtLeastOne",
    presCondArgs: "2",
    dsPresCond: "F",
    children: asgChildren,
  },
  BndWid: {
    tagName: "DataObject",
    name: "BndWid",
    type: "ASG",
    descID: "IEC61850_7_4.LNGroupA::ATCC.BndWid.desc",
    presCond: "O",
    dsPresCond: "F",
    children: asgChildren,
  },
  CtlDlTmms: {
    tagName: "DataObject",
    name: "CtlDlTmms",
    type: "ING",
    descID: "IEC61850_7_4.LNGroupA::ATCC.CtlDlTmms.desc",
    presCond: "O",
    dsPresCond: "F",
    children: ingChildren,
  },
  LDCR: {
    tagName: "DataObject",
    name: "LDCR",
    type: "ASG",
    descID: "IEC61850_7_4.LNGroupA::ATCC.LDCR.desc",
    presCond: "O",
    dsPresCond: "F",
    children: asgChildren,
  },
  LDCX: {
    tagName: "DataObject",
    name: "LDCX",
    type: "ASG",
    descID: "IEC61850_7_4.LNGroupA::ATCC.LDCX.desc",
    presCond: "O",
    dsPresCond: "F",
    children: asgChildren,
  },
  BlkLV: {
    tagName: "DataObject",
    name: "BlkLV",
    type: "ASG",
    descID: "IEC61850_7_4.LNGroupA::ATCC.BlkLV.desc",
    presCond: "O",
    dsPresCond: "F",
    children: asgChildren,
  },
  BlkRV: {
    tagName: "DataObject",
    name: "BlkRV",
    type: "ASG",
    descID: "IEC61850_7_4.LNGroupA::ATCC.BlkRV.desc",
    presCond: "O",
    dsPresCond: "F",
    children: asgChildren,
  },
  BlkVLo: {
    tagName: "DataObject",
    name: "BlkVLo",
    type: "ASG",
    descID: "IEC61850_7_4.LNGroupA::ATCC.BlkVLo.desc",
    presCond: "O",
    dsPresCond: "F",
    children: asgChildren,
  },
  BlkVHi: {
    tagName: "DataObject",
    name: "BlkVHi",
    type: "ASG",
    descID: "IEC61850_7_4.LNGroupA::ATCC.BlkVHi.desc",
    presCond: "O",
    dsPresCond: "F",
    children: asgChildren,
  },
  RnbkRV: {
    tagName: "DataObject",
    name: "RnbkRV",
    type: "ASG",
    descID: "IEC61850_7_4.LNGroupA::ATCC.RnbkRV.desc",
    presCond: "O",
    dsPresCond: "F",
    children: asgChildren,
  },
  LimLodA: {
    tagName: "DataObject",
    name: "LimLodA",
    type: "ASG",
    descID: "IEC61850_7_4.LNGroupA::ATCC.LimLodA.desc",
    presCond: "O",
    dsPresCond: "F",
    children: asgChildren,
  },
  LDC: {
    tagName: "DataObject",
    name: "LDC",
    type: "SPG",
    descID: "IEC61850_7_4.LNGroupA::ATCC.LDC.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spgChildren,
  },
  ParTrfMod: {
    tagName: "DataObject",
    name: "ParTrfMod",
    type: "ENG",
    underlyingType: "ParallelTransfModeKind",
    descID: "IEC61850_7_4.LNGroupA::ATCC.ParTrfMod.desc",
    presCond: "O",
    dsPresCond: "F",
    children: {
      setVal: {
        tagName: "DataAttribute",
        name: "setVal",
        fc: "SE",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.ENG::ENG_SE.setVal.desc",
        mandatory: true,
        presCond: "M",
        type: "ParallelTransfModeKind",
        children: {
          "No Mode predefined": {
            tagName: "Literal",
            name: "No Mode predefined",
            literalVal: "1",
          },
          Master: {
            tagName: "Literal",
            name: "Master",
            literalVal: "2",
          },
          Follower: {
            tagName: "Literal",
            name: "Follower",
            literalVal: "3",
          },
          "Power Factor": {
            tagName: "Literal",
            name: "Power Factor",
            literalVal: "4",
          },
          "Negative Reactance": {
            tagName: "Literal",
            name: "Negative Reactance",
            literalVal: "5",
          },
          "Circulating Current": {
            tagName: "Literal",
            name: "Circulating Current",
            literalVal: "6",
          },
          "Circulating Reactive Current (var balancing)": {
            tagName: "Literal",
            name: "Circulating Reactive Current (var balancing)",
            literalVal: "7",
          },
          "Circulating Reactive Current by equalizing power factor": {
            tagName: "Literal",
            name: "Circulating Reactive Current by equalizing power factor",
            literalVal: "8",
            descID:
              "IEC61850_7_4.DOEnums::ParallelTransfModeKind.Circulating_Reactive_Current_by_equalizing_power_factor.desc",
          },
        },
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  TmDlChr: {
    tagName: "DataObject",
    name: "TmDlChr",
    type: "SPG",
    descID: "IEC61850_7_4.LNGroupA::ATCC.TmDlChr.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spgChildren,
  },
  LDCZ: {
    tagName: "DataObject",
    name: "LDCZ",
    type: "ASG",
    descID: "IEC61850_7_4.LNGroupA::ATCC.LDCZ.desc",
    presCond: "O",
    dsPresCond: "F",
    children: asgChildren,
  },
  VRedVal: {
    tagName: "DataObject",
    name: "VRedVal",
    type: "ASG",
    descID: "IEC61850_7_4.LNGroupA::ATCC.VRedVal.desc",
    deprecated: "true",
    presCond: "O",
    dsPresCond: "F",
    children: asgChildren,
  },
  TapBlkR: {
    tagName: "DataObject",
    name: "TapBlkR",
    type: "ING",
    descID: "IEC61850_7_4.LNGroupA::ATCC.TapBlkR.desc",
    presCond: "O",
    dsPresCond: "F",
    children: ingChildren,
  },
  TapBlkL: {
    tagName: "DataObject",
    name: "TapBlkL",
    type: "ING",
    descID: "IEC61850_7_4.LNGroupA::ATCC.TapBlkL.desc",
    presCond: "O",
    dsPresCond: "F",
    children: ingChildren,
  },
};
