export const dplChildren = {
  vendor: {
    tagName: "DataAttribute",
    name: "vendor",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::DPL.vendor.desc",
    mandatory: true,
    presCond: "M",
  },
  hwRev: {
    tagName: "DataAttribute",
    name: "hwRev",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::DPL.hwRev.desc",
    presCond: "O",
  },
  swRev: {
    tagName: "DataAttribute",
    name: "swRev",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::DPL.swRev.desc",
    presCond: "O",
  },
  serNum: {
    tagName: "DataAttribute",
    name: "serNum",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::DPL.serNum.desc",
    presCond: "O",
  },
  model: {
    tagName: "DataAttribute",
    name: "model",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::DPL.model.desc",
    presCond: "O",
  },
  location: {
    tagName: "DataAttribute",
    name: "location",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::DPL.location.desc",
    presCond: "O",
  },
  name: {
    tagName: "DataAttribute",
    name: "name",
    fc: "DC",
    type: "VisString64",
    descID: "IEC61850_7_3.CDCDescription::DPL.name.desc",
    presCond: "O",
  },
  owner: {
    tagName: "DataAttribute",
    name: "owner",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::DPL.owner.desc",
    presCond: "O",
  },
  ePSName: {
    tagName: "DataAttribute",
    name: "ePSName",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::DPL.ePSName.desc",
    presCond: "O",
  },
  primeOper: {
    tagName: "DataAttribute",
    name: "primeOper",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::DPL.primeOper.desc",
    presCond: "O",
  },
  secondOper: {
    tagName: "DataAttribute",
    name: "secondOper",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::DPL.secondOper.desc",
    presCond: "O",
  },
  latitude: {
    tagName: "DataAttribute",
    name: "latitude",
    fc: "DC",
    type: "FLOAT32",
    descID: "IEC61850_7_3.CDCDescription::DPL.latitude.desc",
    presCond: "O",
  },
  longitude: {
    tagName: "DataAttribute",
    name: "longitude",
    fc: "DC",
    type: "FLOAT32",
    descID: "IEC61850_7_3.CDCDescription::DPL.longitude.desc",
    presCond: "O",
  },
  altitude: {
    tagName: "DataAttribute",
    name: "altitude",
    fc: "DC",
    type: "FLOAT32",
    descID: "IEC61850_7_3.CDCDescription::DPL.altitude.desc",
    presCond: "O",
  },
  mRID: {
    tagName: "DataAttribute",
    name: "mRID",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::DPL.mRID.desc",
    presCond: "O",
  },
  d: {
    tagName: "DataAttribute",
    name: "d",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
    presCond: "O",
  },
  dU: {
    tagName: "DataAttribute",
    name: "dU",
    fc: "DC",
    type: "Unicode255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
    presCond: "O",
  },
  cdcName: {
    tagName: "DataAttribute",
    name: "cdcName",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
    presCond: "O",
  },
  dataNs: {
    tagName: "DataAttribute",
    name: "dataNs",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
    presCond: "MOdataNs",
  },
};
