import { cmvChildren } from "./CMV.js";

export const hmvChildren = {
  har: {
    tagName: "SubDataObject",
    name: "har",
    type: "CMV",
    descID: "IEC61850_7_3.CDCAnalogueInfo::HMV.har.desc",
    mandatory: true,
    presCond: "M",
    isArray: "true",
    sizeAttribute: "maxPts",
    children: cmvChildren,
  },
  numHar: {
    tagName: "DataAttribute",
    name: "numHar",
    fc: "CF",
    type: "INT16U",
    dchg: "true",
    descID: "IEC61850_7_3.CDCAnalogueInfo::HarmonicMeasurandCDC.numHar.desc",
    mandatory: true,
    presCond: "M",
  },
  numCyc: {
    tagName: "DataAttribute",
    name: "numCyc",
    fc: "CF",
    type: "INT16U",
    dchg: "true",
    descID: "IEC61850_7_3.CDCAnalogueInfo::HarmonicMeasurandCDC.numCyc.desc",
    mandatory: true,
    presCond: "M",
  },
  evalTm: {
    tagName: "DataAttribute",
    name: "evalTm",
    fc: "CF",
    type: "INT16U",
    dchg: "true",
    descID: "IEC61850_7_3.CDCAnalogueInfo::HarmonicMeasurandCDC.evalTm.desc",
    mandatory: true,
    presCond: "M",
  },
  smpRate: {
    tagName: "DataAttribute",
    name: "smpRate",
    fc: "CF",
    type: "INT32U",
    dchg: "true",
    descID: "IEC61850_7_3.CDCAnalogueInfo::HarmonicMeasurandCDC.smpRate.desc",
    presCond: "O",
  },
  frequency: {
    tagName: "DataAttribute",
    name: "frequency",
    fc: "CF",
    type: "FLOAT32",
    dchg: "true",
    descID: "IEC61850_7_3.CDCAnalogueInfo::HarmonicMeasurandCDC.frequency.desc",
    mandatory: true,
    presCond: "M",
  },
  hvRef: {
    tagName: "DataAttribute",
    name: "hvRef",
    fc: "CF",
    type: "HvReferenceKind",
    typeKind: "ENUMERATED",
    dchg: "true",
    descID: "IEC61850_7_3.CDCAnalogueInfo::HarmonicMeasurandCDC.hvRef.desc",
    presCond: "O",
    children: {
      fundamental: {
        tagName: "Literal",
        name: "fundamental",
        literalVal: "0",
      },
      rms: {
        tagName: "Literal",
        name: "rms",
        literalVal: "1",
      },
      absolute: {
        tagName: "Literal",
        name: "absolute",
        literalVal: "2",
      },
    },
  },
  rmsCyc: {
    tagName: "DataAttribute",
    name: "rmsCyc",
    fc: "CF",
    type: "INT16U",
    dchg: "true",
    descID: "IEC61850_7_3.CDCAnalogueInfo::HarmonicMeasurandCDC.rmsCyc.desc",
    presCond: "MOrms",
  },
  maxPts: {
    tagName: "DataAttribute",
    name: "maxPts",
    fc: "CF",
    type: "INT16U",
    dchg: "true",
    descID: "IEC61850_7_3.CDCAnalogueInfo::HarmonicMeasurandCDC.maxPts.desc",
    mandatory: true,
    presCond: "M",
  },
  d: {
    tagName: "DataAttribute",
    name: "d",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BaseComposedCDC.d.desc",
    presCond: "O",
  },
  dU: {
    tagName: "DataAttribute",
    name: "dU",
    fc: "DC",
    type: "Unicode255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BaseComposedCDC.dU.desc",
    presCond: "O",
  },
  cdcName: {
    tagName: "DataAttribute",
    name: "cdcName",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BaseComposedCDC.cdcName.desc",
    presCond: "O",
  },
  dataNs: {
    tagName: "DataAttribute",
    name: "dataNs",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BaseComposedCDC.dataNs.desc",
    presCond: "MOdataNs",
  },
};
