export const lplChildren = {
  paramRev: {
    tagName: "DataAttribute",
    name: "paramRev",
    fc: "ST",
    type: "INT32",
    dchg: "true",
    descID: "IEC61850_7_3.CDCDescription::LPL.paramRev.desc",
    presCond: "O",
  },
  valRev: {
    tagName: "DataAttribute",
    name: "valRev",
    fc: "ST",
    type: "INT32",
    dchg: "true",
    descID: "IEC61850_7_3.CDCDescription::LPL.valRev.desc",
    presCond: "O",
  },
  vendor: {
    tagName: "DataAttribute",
    name: "vendor",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::LPL.vendor.desc",
    mandatory: true,
    presCond: "M",
  },
  swRev: {
    tagName: "DataAttribute",
    name: "swRev",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::LPL.swRev.desc",
    mandatory: true,
    presCond: "M",
  },
  ldNs: {
    tagName: "DataAttribute",
    name: "ldNs",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::LPL.ldNs.desc",
    presCond: "MFln0",
  },
  lnNs: {
    tagName: "DataAttribute",
    name: "lnNs",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::LPL.lnNs.desc",
    presCond: "MOlnNs",
  },
  d: {
    tagName: "DataAttribute",
    name: "d",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
    presCond: "O",
  },
  dU: {
    tagName: "DataAttribute",
    name: "dU",
    fc: "DC",
    type: "Unicode255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
    presCond: "O",
  },
  configRev: {
    tagName: "DataAttribute",
    name: "configRev",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CDCDescription::LPL.configRev.desc",
    presCond: "MOln0",
  },
  cdcName: {
    tagName: "DataAttribute",
    name: "cdcName",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
    presCond: "O",
  },
  dataNs: {
    tagName: "DataAttribute",
    name: "dataNs",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
    presCond: "MOdataNs",
  },
};
