import { ingChildren } from "./ING.js";
import { insChildren } from "./INS.js";
import { lplChildren } from "./LPL.js";
import { orgChildren } from "./ORG.js";
import { spsChildren } from "./SPS.js";
import { vsgChildren } from "./VSG.js";
import { vssChildren } from "./VSS.js";

export const ltms = {
  NamPlt: {
    tagName: "DataObject",
    name: "NamPlt",
    type: "LPL",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.NamPlt.desc",
    presCond: "MONamPlt",
    presCondArgsID:
      "IEC61850_7_4.AbstractLNsCommon::DomainLN__(_MONamPlt_=__((_NamPlt_))__)_.cond.AbstractLNsCommon::DomainLN.NamPlt",
    dsPresCond: "MONamPlt",
    dsPresCondArgsID:
      "IEC61850_7_4.AbstractLNsCommon::DomainLN__(_MONamPlt_=__((_NamPlt_))__)_.dsCond.AbstractLNsCommon::DomainLN.NamPlt",
    children: lplChildren,
  },
  Beh: {
    tagName: "DataObject",
    name: "Beh",
    type: "ENS",
    underlyingType: "BehaviourModeKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.Beh.desc",
    mandatory: true,
    presCond: "M",
    dsPresCond: "M",
    children: {
      stVal: {
        tagName: "DataAttribute",
        name: "stVal",
        fc: "ST",
        typeKind: "ENUMERATED",
        dchg: "true",
        dupd: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.stVal.desc",
        mandatory: true,
        presCond: "M",
        type: "BehaviourModeKind",
        children: {
          on: {
            tagName: "Literal",
            name: "on",
            literalVal: "1",
          },
          blocked: {
            tagName: "Literal",
            name: "blocked",
            literalVal: "2",
          },
          test: {
            tagName: "Literal",
            name: "test",
            literalVal: "3",
          },
          "test/blocked": {
            tagName: "Literal",
            name: "test/blocked",
            literalVal: "4",
          },
          off: {
            tagName: "Literal",
            name: "off",
            literalVal: "5",
          },
        },
      },
      q: {
        tagName: "DataAttribute",
        name: "q",
        fc: "ST",
        type: "Quality",
        qchg: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.q.desc",
        mandatory: true,
        presCond: "M",
      },
      t: {
        tagName: "DataAttribute",
        name: "t",
        fc: "ST",
        type: "Timestamp",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.t.desc",
        mandatory: true,
        presCond: "M",
      },
      subEna: {
        tagName: "DataAttribute",
        name: "subEna",
        fc: "SV",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subEna.desc",
        presCond: "MFsubst",
      },
      subVal: {
        tagName: "DataAttribute",
        name: "subVal",
        fc: "SV",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.subVal.desc",
        presCond: "MFsubst",
        type: "BehaviourModeKind",
        children: {
          on: {
            tagName: "Literal",
            name: "on",
            literalVal: "1",
          },
          blocked: {
            tagName: "Literal",
            name: "blocked",
            literalVal: "2",
          },
          test: {
            tagName: "Literal",
            name: "test",
            literalVal: "3",
          },
          "test/blocked": {
            tagName: "Literal",
            name: "test/blocked",
            literalVal: "4",
          },
          off: {
            tagName: "Literal",
            name: "off",
            literalVal: "5",
          },
        },
      },
      subQ: {
        tagName: "DataAttribute",
        name: "subQ",
        fc: "SV",
        type: "Quality",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subQ.desc",
        presCond: "MFsubst",
      },
      subID: {
        tagName: "DataAttribute",
        name: "subID",
        fc: "SV",
        type: "VisString64",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subID.desc",
        presCond: "MFsubst",
      },
      blkEna: {
        tagName: "DataAttribute",
        name: "blkEna",
        fc: "BL",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.blkEna.desc",
        presCond: "O",
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  Health: {
    tagName: "DataObject",
    name: "Health",
    type: "ENS",
    underlyingType: "HealthKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.Health.desc",
    presCond: "O",
    dsPresCond: "O",
    children: {
      stVal: {
        tagName: "DataAttribute",
        name: "stVal",
        fc: "ST",
        typeKind: "ENUMERATED",
        dchg: "true",
        dupd: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.stVal.desc",
        mandatory: true,
        presCond: "M",
        type: "HealthKind",
        children: {
          Ok: {
            tagName: "Literal",
            name: "Ok",
            literalVal: "1",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Ok.desc",
          },
          Warning: {
            tagName: "Literal",
            name: "Warning",
            literalVal: "2",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Warning.desc",
          },
          Alarm: {
            tagName: "Literal",
            name: "Alarm",
            literalVal: "3",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Alarm.desc",
          },
        },
      },
      q: {
        tagName: "DataAttribute",
        name: "q",
        fc: "ST",
        type: "Quality",
        qchg: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.q.desc",
        mandatory: true,
        presCond: "M",
      },
      t: {
        tagName: "DataAttribute",
        name: "t",
        fc: "ST",
        type: "Timestamp",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.t.desc",
        mandatory: true,
        presCond: "M",
      },
      subEna: {
        tagName: "DataAttribute",
        name: "subEna",
        fc: "SV",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subEna.desc",
        presCond: "MFsubst",
      },
      subVal: {
        tagName: "DataAttribute",
        name: "subVal",
        fc: "SV",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.subVal.desc",
        presCond: "MFsubst",
        type: "HealthKind",
        children: {
          Ok: {
            tagName: "Literal",
            name: "Ok",
            literalVal: "1",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Ok.desc",
          },
          Warning: {
            tagName: "Literal",
            name: "Warning",
            literalVal: "2",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Warning.desc",
          },
          Alarm: {
            tagName: "Literal",
            name: "Alarm",
            literalVal: "3",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Alarm.desc",
          },
        },
      },
      subQ: {
        tagName: "DataAttribute",
        name: "subQ",
        fc: "SV",
        type: "Quality",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subQ.desc",
        presCond: "MFsubst",
      },
      subID: {
        tagName: "DataAttribute",
        name: "subID",
        fc: "SV",
        type: "VisString64",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subID.desc",
        presCond: "MFsubst",
      },
      blkEna: {
        tagName: "DataAttribute",
        name: "blkEna",
        fc: "BL",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.blkEna.desc",
        presCond: "O",
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  Mir: {
    tagName: "DataObject",
    name: "Mir",
    type: "SPS",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.Mir.desc",
    presCond: "MOcond",
    presCondArgs: "1",
    presCondArgsID:
      "IEC61850_7_4.AbstractLNsCommon::DomainLN__(_MOcond(1)_=__((_Mir_))__)_.cond.AbstractLNsCommon::DomainLN.Mir",
    dsPresCond: "MOcond",
    dsPresCondArgs: "1",
    dsPresCondArgsID:
      "IEC61850_7_4.AbstractLNsCommon::DomainLN__(_MOcond(1)_=__((_Mir_))__)_.dsCond.AbstractLNsCommon::DomainLN.Mir",
    children: spsChildren,
  },
  Mod: {
    tagName: "DataObject",
    name: "Mod",
    type: "ENC",
    underlyingType: "BehaviourModeKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.Mod.desc",
    presCond: "O",
    dsPresCond: "O",
    children: {
      origin: {
        tagName: "DataAttribute",
        name: "origin",
        fc: "ST",
        type: "Originator",
        typeKind: "CONSTRUCTED",
        descID: "IEC61850_7_3.CDCControl::ENC.origin.desc",
        presCond: "O",
        children: {
          orCat: {
            tagName: "SubDataAttribute",
            name: "orCat",
            type: "OriginatorCategoryKind",
            typeKind: "ENUMERATED",
            descID: "IEC61850_7_2.DomainTypesGeneral::S_Originator.orCat.desc",
            mandatory: true,
            presCond: "M",
            children: {
              "not-supported": {
                tagName: "Literal",
                name: "not-supported",
                literalVal: "0",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.not-supported.desc",
              },
              "bay-control": {
                tagName: "Literal",
                name: "bay-control",
                literalVal: "1",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.bay-control.desc",
              },
              "station-control": {
                tagName: "Literal",
                name: "station-control",
                literalVal: "2",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.station-control.desc",
              },
              "remote-control": {
                tagName: "Literal",
                name: "remote-control",
                literalVal: "3",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.remote-control.desc",
              },
              "automatic-bay": {
                tagName: "Literal",
                name: "automatic-bay",
                literalVal: "4",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-bay.desc",
              },
              "automatic-station": {
                tagName: "Literal",
                name: "automatic-station",
                literalVal: "5",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-station.desc",
              },
              "automatic-remote": {
                tagName: "Literal",
                name: "automatic-remote",
                literalVal: "6",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-remote.desc",
              },
              maintenance: {
                tagName: "Literal",
                name: "maintenance",
                literalVal: "7",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.maintenance.desc",
              },
              process: {
                tagName: "Literal",
                name: "process",
                literalVal: "8",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.process.desc",
              },
            },
          },
          orIdent: {
            tagName: "SubDataAttribute",
            name: "orIdent",
            type: "Octet64",
            descID:
              "IEC61850_7_2.DomainTypesGeneral::S_Originator.orIdent.desc",
            mandatory: true,
            presCond: "M",
          },
        },
      },
      ctlNum: {
        tagName: "DataAttribute",
        name: "ctlNum",
        fc: "ST",
        type: "INT8U",
        descID: "IEC61850_7_3.CDCControl::ENC.ctlNum.desc",
        presCond: "O",
      },
      stVal: {
        tagName: "DataAttribute",
        name: "stVal",
        fc: "ST",
        typeKind: "ENUMERATED",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.stVal.desc",
        mandatory: true,
        presCond: "M",
        type: "BehaviourModeKind",
        children: {
          on: {
            tagName: "Literal",
            name: "on",
            literalVal: "1",
          },
          blocked: {
            tagName: "Literal",
            name: "blocked",
            literalVal: "2",
          },
          test: {
            tagName: "Literal",
            name: "test",
            literalVal: "3",
          },
          "test/blocked": {
            tagName: "Literal",
            name: "test/blocked",
            literalVal: "4",
          },
          off: {
            tagName: "Literal",
            name: "off",
            literalVal: "5",
          },
        },
      },
      q: {
        tagName: "DataAttribute",
        name: "q",
        fc: "ST",
        type: "Quality",
        qchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.q.desc",
        mandatory: true,
        presCond: "M",
      },
      t: {
        tagName: "DataAttribute",
        name: "t",
        fc: "ST",
        type: "Timestamp",
        descID: "IEC61850_7_3.CDCControl::ENC.t.desc",
        mandatory: true,
        presCond: "M",
      },
      stSeld: {
        tagName: "DataAttribute",
        name: "stSeld",
        fc: "ST",
        type: "BOOLEAN",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.stSeld.desc",
        presCond: "MOsbo",
      },
      opRcvd: {
        tagName: "DataAttribute",
        name: "opRcvd",
        fc: "OR",
        type: "BOOLEAN",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ControlTestingCDC.opRcvd.desc",
        presCond: "O",
      },
      opOk: {
        tagName: "DataAttribute",
        name: "opOk",
        fc: "OR",
        type: "BOOLEAN",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ControlTestingCDC.opOk.desc",
        presCond: "O",
      },
      tOpOk: {
        tagName: "DataAttribute",
        name: "tOpOk",
        fc: "OR",
        type: "Timestamp",
        descID: "IEC61850_7_3.CDCControl::ControlTestingCDC.tOpOk.desc",
        presCond: "O",
      },
      subEna: {
        tagName: "DataAttribute",
        name: "subEna",
        fc: "SV",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subEna.desc",
        presCond: "MFsubst",
      },
      subVal: {
        tagName: "DataAttribute",
        name: "subVal",
        fc: "SV",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.CDCControl::ENC.subVal.desc",
        presCond: "MFsubst",
        type: "BehaviourModeKind",
        children: {
          on: {
            tagName: "Literal",
            name: "on",
            literalVal: "1",
          },
          blocked: {
            tagName: "Literal",
            name: "blocked",
            literalVal: "2",
          },
          test: {
            tagName: "Literal",
            name: "test",
            literalVal: "3",
          },
          "test/blocked": {
            tagName: "Literal",
            name: "test/blocked",
            literalVal: "4",
          },
          off: {
            tagName: "Literal",
            name: "off",
            literalVal: "5",
          },
        },
      },
      subQ: {
        tagName: "DataAttribute",
        name: "subQ",
        fc: "SV",
        type: "Quality",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subQ.desc",
        presCond: "MFsubst",
      },
      subID: {
        tagName: "DataAttribute",
        name: "subID",
        fc: "SV",
        type: "VisString64",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subID.desc",
        presCond: "MFsubst",
      },
      blkEna: {
        tagName: "DataAttribute",
        name: "blkEna",
        fc: "BL",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.blkEna.desc",
        presCond: "O",
      },
      ctlModel: {
        tagName: "DataAttribute",
        name: "ctlModel",
        fc: "CF",
        type: "CtlModelKind",
        typeKind: "ENUMERATED",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.ctlModel.desc",
        mandatory: true,
        presCond: "M",
        children: {
          "status-only": {
            tagName: "Literal",
            name: "status-only",
            literalVal: "0",
            descID: "IEC61850_7_3.DAEnums::CtlModelKind.status-only.desc",
          },
          "direct-with-normal-security": {
            tagName: "Literal",
            name: "direct-with-normal-security",
            literalVal: "1",
            descID:
              "IEC61850_7_3.DAEnums::CtlModelKind.direct-with-normal-security.desc",
          },
          "sbo-with-normal-security": {
            tagName: "Literal",
            name: "sbo-with-normal-security",
            literalVal: "2",
            descID:
              "IEC61850_7_3.DAEnums::CtlModelKind.sbo-with-normal-security.desc",
          },
          "direct-with-enhanced-security": {
            tagName: "Literal",
            name: "direct-with-enhanced-security",
            literalVal: "3",
            descID:
              "IEC61850_7_3.DAEnums::CtlModelKind.direct-with-enhanced-security.desc",
          },
          "sbo-with-enhanced-security": {
            tagName: "Literal",
            name: "sbo-with-enhanced-security",
            literalVal: "4",
            descID:
              "IEC61850_7_3.DAEnums::CtlModelKind.sbo-with-enhanced-security.desc",
          },
        },
      },
      sboTimeout: {
        tagName: "DataAttribute",
        name: "sboTimeout",
        fc: "CF",
        type: "INT32U",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.sboTimeout.desc",
        presCond: "MOsbo",
      },
      sboClass: {
        tagName: "DataAttribute",
        name: "sboClass",
        fc: "CF",
        type: "SboClassKind",
        typeKind: "ENUMERATED",
        defaultValue: "operate-once",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.sboClass.desc",
        presCond: "O",
        children: {
          "operate-once": {
            tagName: "Literal",
            name: "operate-once",
            literalVal: "0",
            descID: "IEC61850_7_3.DAEnums::SboClassKind.operate-once.desc",
          },
          "operate-many": {
            tagName: "Literal",
            name: "operate-many",
            literalVal: "1",
            descID: "IEC61850_7_3.DAEnums::SboClassKind.operate-many.desc",
          },
        },
      },
      operTimeout: {
        tagName: "DataAttribute",
        name: "operTimeout",
        fc: "CF",
        type: "INT32U",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.operTimeout.desc",
        presCond: "MOenhanced",
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
      SBO: {
        tagName: "ServiceDataAttribute",
        name: "SBO",
        typeKind: "BASIC",
        type: "VisString129",
        fc: "CO",
        presCond: "MOsboNormal",
        descID: "IEC 61850-8-1:2003.SBO",
      },
      SBOw: {
        tagName: "ServiceDataAttribute",
        name: "SBOw",
        typeKind: "CONSTRUCTED",
        type: "SBOw",
        underlyingTypeKind: "ENUMERATED",
        fc: "CO",
        presCond: "MOsboEnhanced",
        children: {
          ctlVal: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlVal",
            name: "ctlVal",
            typeKind: "undefined",
            mandatory: true,
            presCond: "M",
          },
          operTm: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.operTm",
            name: "operTm",
            typeKind: "BASIC",
            type: "Timestamp",
            presCond: "MOoperTm",
          },
          origin: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.origin",
            name: "origin",
            typeKind: "CONSTRUCTED",
            type: "Originator",
            mandatory: true,
            presCond: "M",
            children: {
              orCat: {
                tagName: "SubDataAttribute",
                name: "orCat",
                type: "OriginatorCategoryKind",
                typeKind: "ENUMERATED",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orCat.desc",
                mandatory: true,
                presCond: "M",
                children: {
                  "not-supported": {
                    tagName: "Literal",
                    name: "not-supported",
                    literalVal: "0",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.not-supported.desc",
                  },
                  "bay-control": {
                    tagName: "Literal",
                    name: "bay-control",
                    literalVal: "1",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.bay-control.desc",
                  },
                  "station-control": {
                    tagName: "Literal",
                    name: "station-control",
                    literalVal: "2",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.station-control.desc",
                  },
                  "remote-control": {
                    tagName: "Literal",
                    name: "remote-control",
                    literalVal: "3",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.remote-control.desc",
                  },
                  "automatic-bay": {
                    tagName: "Literal",
                    name: "automatic-bay",
                    literalVal: "4",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-bay.desc",
                  },
                  "automatic-station": {
                    tagName: "Literal",
                    name: "automatic-station",
                    literalVal: "5",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-station.desc",
                  },
                  "automatic-remote": {
                    tagName: "Literal",
                    name: "automatic-remote",
                    literalVal: "6",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-remote.desc",
                  },
                  maintenance: {
                    tagName: "Literal",
                    name: "maintenance",
                    literalVal: "7",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.maintenance.desc",
                  },
                  process: {
                    tagName: "Literal",
                    name: "process",
                    literalVal: "8",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.process.desc",
                  },
                },
              },
              orIdent: {
                tagName: "SubDataAttribute",
                name: "orIdent",
                type: "Octet64",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orIdent.desc",
                mandatory: true,
                presCond: "M",
              },
            },
          },
          ctlNum: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlNum",
            name: "ctlNum",
            typeKind: "BASIC",
            type: "INT8U",
            mandatory: true,
            presCond: "M",
          },
          T: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.T",
            name: "T",
            typeKind: "BASIC",
            type: "Timestamp",
            mandatory: true,
            presCond: "M",
          },
          Test: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.Test",
            name: "Test",
            typeKind: "BASIC",
            type: "BOOLEAN",
            mandatory: true,
            presCond: "M",
          },
          Check: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.Check",
            name: "Check",
            typeKind: "BASIC",
            type: "Check",
            mandatory: true,
            presCond: "M",
          },
        },
      },
      Oper: {
        tagName: "ServiceDataAttribute",
        name: "Oper",
        typeKind: "CONSTRUCTED",
        type: "Oper",
        underlyingTypeKind: "ENUMERATED",
        fc: "CO",
        presCond: "MOctrl",
        children: {
          ctlVal: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlVal",
            name: "ctlVal",
            typeKind: "undefined",
            mandatory: true,
            presCond: "M",
          },
          operTm: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.operTm",
            name: "operTm",
            typeKind: "BASIC",
            type: "Timestamp",
            presCond: "MOoperTm",
          },
          origin: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.origin",
            name: "origin",
            typeKind: "CONSTRUCTED",
            type: "Originator",
            mandatory: true,
            presCond: "M",
            children: {
              orCat: {
                tagName: "SubDataAttribute",
                name: "orCat",
                type: "OriginatorCategoryKind",
                typeKind: "ENUMERATED",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orCat.desc",
                mandatory: true,
                presCond: "M",
                children: {
                  "not-supported": {
                    tagName: "Literal",
                    name: "not-supported",
                    literalVal: "0",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.not-supported.desc",
                  },
                  "bay-control": {
                    tagName: "Literal",
                    name: "bay-control",
                    literalVal: "1",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.bay-control.desc",
                  },
                  "station-control": {
                    tagName: "Literal",
                    name: "station-control",
                    literalVal: "2",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.station-control.desc",
                  },
                  "remote-control": {
                    tagName: "Literal",
                    name: "remote-control",
                    literalVal: "3",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.remote-control.desc",
                  },
                  "automatic-bay": {
                    tagName: "Literal",
                    name: "automatic-bay",
                    literalVal: "4",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-bay.desc",
                  },
                  "automatic-station": {
                    tagName: "Literal",
                    name: "automatic-station",
                    literalVal: "5",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-station.desc",
                  },
                  "automatic-remote": {
                    tagName: "Literal",
                    name: "automatic-remote",
                    literalVal: "6",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-remote.desc",
                  },
                  maintenance: {
                    tagName: "Literal",
                    name: "maintenance",
                    literalVal: "7",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.maintenance.desc",
                  },
                  process: {
                    tagName: "Literal",
                    name: "process",
                    literalVal: "8",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.process.desc",
                  },
                },
              },
              orIdent: {
                tagName: "SubDataAttribute",
                name: "orIdent",
                type: "Octet64",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orIdent.desc",
                mandatory: true,
                presCond: "M",
              },
            },
          },
          ctlNum: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlNum",
            name: "ctlNum",
            typeKind: "BASIC",
            type: "INT8U",
            mandatory: true,
            presCond: "M",
          },
          T: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.T",
            name: "T",
            typeKind: "BASIC",
            type: "Timestamp",
            mandatory: true,
            presCond: "M",
          },
          Test: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.Test",
            name: "Test",
            typeKind: "BASIC",
            type: "BOOLEAN",
            mandatory: true,
            presCond: "M",
          },
          Check: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.Check",
            name: "Check",
            typeKind: "BASIC",
            type: "Check",
            mandatory: true,
            presCond: "M",
          },
        },
      },
      Cancel: {
        tagName: "ServiceDataAttribute",
        name: "Cancel",
        typeKind: "CONSTRUCTED",
        type: "Cancel",
        underlyingTypeKind: "ENUMERATED",
        fc: "CO",
        presCond: "MOsbo",
        children: {
          ctlVal: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlVal",
            name: "ctlVal",
            typeKind: "undefined",
            mandatory: true,
            presCond: "M",
          },
          operTm: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.operTm",
            name: "operTm",
            typeKind: "BASIC",
            type: "Timestamp",
            presCond: "MOoperTm",
          },
          origin: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.origin",
            name: "origin",
            typeKind: "CONSTRUCTED",
            type: "Originator",
            mandatory: true,
            presCond: "M",
            children: {
              orCat: {
                tagName: "SubDataAttribute",
                name: "orCat",
                type: "OriginatorCategoryKind",
                typeKind: "ENUMERATED",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orCat.desc",
                mandatory: true,
                presCond: "M",
                children: {
                  "not-supported": {
                    tagName: "Literal",
                    name: "not-supported",
                    literalVal: "0",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.not-supported.desc",
                  },
                  "bay-control": {
                    tagName: "Literal",
                    name: "bay-control",
                    literalVal: "1",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.bay-control.desc",
                  },
                  "station-control": {
                    tagName: "Literal",
                    name: "station-control",
                    literalVal: "2",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.station-control.desc",
                  },
                  "remote-control": {
                    tagName: "Literal",
                    name: "remote-control",
                    literalVal: "3",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.remote-control.desc",
                  },
                  "automatic-bay": {
                    tagName: "Literal",
                    name: "automatic-bay",
                    literalVal: "4",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-bay.desc",
                  },
                  "automatic-station": {
                    tagName: "Literal",
                    name: "automatic-station",
                    literalVal: "5",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-station.desc",
                  },
                  "automatic-remote": {
                    tagName: "Literal",
                    name: "automatic-remote",
                    literalVal: "6",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-remote.desc",
                  },
                  maintenance: {
                    tagName: "Literal",
                    name: "maintenance",
                    literalVal: "7",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.maintenance.desc",
                  },
                  process: {
                    tagName: "Literal",
                    name: "process",
                    literalVal: "8",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.process.desc",
                  },
                },
              },
              orIdent: {
                tagName: "SubDataAttribute",
                name: "orIdent",
                type: "Octet64",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orIdent.desc",
                mandatory: true,
                presCond: "M",
              },
            },
          },
          ctlNum: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlNum",
            name: "ctlNum",
            typeKind: "BASIC",
            type: "INT8U",
            mandatory: true,
            presCond: "M",
          },
          T: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.T",
            name: "T",
            typeKind: "BASIC",
            type: "Timestamp",
            mandatory: true,
            presCond: "M",
          },
          Test: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.Test",
            name: "Test",
            typeKind: "BASIC",
            type: "BOOLEAN",
            mandatory: true,
            presCond: "M",
          },
        },
      },
    },
  },
  InRef1: {
    tagName: "DataObject",
    name: "InRef1",
    type: "ORG",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.InRef.desc",
    presCond: "Omulti",
    dsPresCond: "Omulti",
    children: orgChildren,
  },
  TmAcc: {
    tagName: "DataObject",
    name: "TmAcc",
    type: "INS",
    descID: "IEC61850_7_4.LNGroupL::LTMS.TmAcc.desc",
    presCond: "O",
    dsPresCond: "na",
    children: insChildren,
  },
  TmSrc: {
    tagName: "DataObject",
    name: "TmSrc",
    type: "VSS",
    descID: "IEC61850_7_4.LNGroupL::LTMS.TmSrc.desc",
    mandatory: true,
    presCond: "M",
    dsPresCond: "na",
    children: vssChildren,
  },
  TmSrcTyp: {
    tagName: "DataObject",
    name: "TmSrcTyp",
    type: "ENS",
    underlyingType: "ClockSourceKind",
    descID: "IEC61850_7_4.LNGroupL::LTMS.TmSrcTyp.desc",
    mandatory: true,
    presCond: "M",
    dsPresCond: "na",
    children: {
      stVal: {
        tagName: "DataAttribute",
        name: "stVal",
        fc: "ST",
        typeKind: "ENUMERATED",
        dchg: "true",
        dupd: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.stVal.desc",
        mandatory: true,
        presCond: "M",
        type: "ClockSourceKind",
        children: {
          Unknown: {
            tagName: "Literal",
            name: "Unknown",
            literalVal: "1",
          },
          SNTP: {
            tagName: "Literal",
            name: "SNTP",
            literalVal: "2",
          },
          PTP: {
            tagName: "Literal",
            name: "PTP",
            literalVal: "3",
          },
          "IRIG-B": {
            tagName: "Literal",
            name: "IRIG-B",
            literalVal: "4",
          },
          "Substation internal": {
            tagName: "Literal",
            name: "Substation internal",
            literalVal: "5",
          },
        },
      },
      q: {
        tagName: "DataAttribute",
        name: "q",
        fc: "ST",
        type: "Quality",
        qchg: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.q.desc",
        mandatory: true,
        presCond: "M",
      },
      t: {
        tagName: "DataAttribute",
        name: "t",
        fc: "ST",
        type: "Timestamp",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.t.desc",
        mandatory: true,
        presCond: "M",
      },
      subEna: {
        tagName: "DataAttribute",
        name: "subEna",
        fc: "SV",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subEna.desc",
        presCond: "MFsubst",
      },
      subVal: {
        tagName: "DataAttribute",
        name: "subVal",
        fc: "SV",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.subVal.desc",
        presCond: "MFsubst",
        type: "ClockSourceKind",
        children: {
          Unknown: {
            tagName: "Literal",
            name: "Unknown",
            literalVal: "1",
          },
          SNTP: {
            tagName: "Literal",
            name: "SNTP",
            literalVal: "2",
          },
          PTP: {
            tagName: "Literal",
            name: "PTP",
            literalVal: "3",
          },
          "IRIG-B": {
            tagName: "Literal",
            name: "IRIG-B",
            literalVal: "4",
          },
          "Substation internal": {
            tagName: "Literal",
            name: "Substation internal",
            literalVal: "5",
          },
        },
      },
      subQ: {
        tagName: "DataAttribute",
        name: "subQ",
        fc: "SV",
        type: "Quality",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subQ.desc",
        presCond: "MFsubst",
      },
      subID: {
        tagName: "DataAttribute",
        name: "subID",
        fc: "SV",
        type: "VisString64",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subID.desc",
        presCond: "MFsubst",
      },
      blkEna: {
        tagName: "DataAttribute",
        name: "blkEna",
        fc: "BL",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.blkEna.desc",
        presCond: "O",
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  TmSyn: {
    tagName: "DataObject",
    name: "TmSyn",
    type: "ENS",
    underlyingType: "ClockSyncKind",
    descID: "IEC61850_7_4.LNGroupL::LTMS.TmSyn.desc",
    presCond: "O",
    dsPresCond: "na",
    children: {
      stVal: {
        tagName: "DataAttribute",
        name: "stVal",
        fc: "ST",
        typeKind: "ENUMERATED",
        dchg: "true",
        dupd: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.stVal.desc",
        mandatory: true,
        presCond: "M",
        type: "ClockSyncKind",
        children: {
          InternalClock: {
            tagName: "Literal",
            name: "InternalClock",
            literalVal: "0",
          },
          LocalAreaClock: {
            tagName: "Literal",
            name: "LocalAreaClock",
            literalVal: "1",
          },
          GlobalAreaClock: {
            tagName: "Literal",
            name: "GlobalAreaClock",
            literalVal: "2",
          },
        },
      },
      q: {
        tagName: "DataAttribute",
        name: "q",
        fc: "ST",
        type: "Quality",
        qchg: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.q.desc",
        mandatory: true,
        presCond: "M",
      },
      t: {
        tagName: "DataAttribute",
        name: "t",
        fc: "ST",
        type: "Timestamp",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.t.desc",
        mandatory: true,
        presCond: "M",
      },
      subEna: {
        tagName: "DataAttribute",
        name: "subEna",
        fc: "SV",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subEna.desc",
        presCond: "MFsubst",
      },
      subVal: {
        tagName: "DataAttribute",
        name: "subVal",
        fc: "SV",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.subVal.desc",
        presCond: "MFsubst",
        type: "ClockSyncKind",
        children: {
          InternalClock: {
            tagName: "Literal",
            name: "InternalClock",
            literalVal: "0",
          },
          LocalAreaClock: {
            tagName: "Literal",
            name: "LocalAreaClock",
            literalVal: "1",
          },
          GlobalAreaClock: {
            tagName: "Literal",
            name: "GlobalAreaClock",
            literalVal: "2",
          },
        },
      },
      subQ: {
        tagName: "DataAttribute",
        name: "subQ",
        fc: "SV",
        type: "Quality",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subQ.desc",
        presCond: "MFsubst",
      },
      subID: {
        tagName: "DataAttribute",
        name: "subID",
        fc: "SV",
        type: "VisString64",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subID.desc",
        presCond: "MFsubst",
      },
      blkEna: {
        tagName: "DataAttribute",
        name: "blkEna",
        fc: "BL",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.blkEna.desc",
        presCond: "O",
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  TmChSt1: {
    tagName: "DataObject",
    name: "TmChSt1",
    type: "SPS",
    descID: "IEC61850_7_4.LNGroupL::LTMS.TmChSt.desc",
    presCond: "Omulti",
    dsPresCond: "na",
    children: spsChildren,
  },
  TmSynLkd: {
    tagName: "DataObject",
    name: "TmSynLkd",
    type: "ENS",
    underlyingType: "ClockSyncLockingKind",
    descID: "IEC61850_7_4.LNGroupL::LTMS.TmSynLkd.desc",
    presCond: "O",
    dsPresCond: "na",
    children: {
      stVal: {
        tagName: "DataAttribute",
        name: "stVal",
        fc: "ST",
        typeKind: "ENUMERATED",
        dchg: "true",
        dupd: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.stVal.desc",
        mandatory: true,
        presCond: "M",
        type: "ClockSyncLockingKind",
        children: {
          Locked: {
            tagName: "Literal",
            name: "Locked",
            literalVal: "1",
            descID: "IEC61850_7_4.DOEnums::ClockSyncLockingKind.Locked.desc",
          },
          Unlocked10s: {
            tagName: "Literal",
            name: "Unlocked10s",
            literalVal: "2",
            descID:
              "IEC61850_7_4.DOEnums::ClockSyncLockingKind.Unlocked10s.desc",
          },
          Unlocked100s: {
            tagName: "Literal",
            name: "Unlocked100s",
            literalVal: "3",
            descID:
              "IEC61850_7_4.DOEnums::ClockSyncLockingKind.Unlocked100s.desc",
          },
          Unlocked1000s: {
            tagName: "Literal",
            name: "Unlocked1000s",
            literalVal: "4",
            descID:
              "IEC61850_7_4.DOEnums::ClockSyncLockingKind.Unlocked1000s.desc",
          },
          UnlockedMoreThan1000s: {
            tagName: "Literal",
            name: "UnlockedMoreThan1000s",
            literalVal: "5",
            descID:
              "IEC61850_7_4.DOEnums::ClockSyncLockingKind.UnlockedMoreThan1000s.desc",
          },
        },
      },
      q: {
        tagName: "DataAttribute",
        name: "q",
        fc: "ST",
        type: "Quality",
        qchg: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.q.desc",
        mandatory: true,
        presCond: "M",
      },
      t: {
        tagName: "DataAttribute",
        name: "t",
        fc: "ST",
        type: "Timestamp",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.t.desc",
        mandatory: true,
        presCond: "M",
      },
      subEna: {
        tagName: "DataAttribute",
        name: "subEna",
        fc: "SV",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subEna.desc",
        presCond: "MFsubst",
      },
      subVal: {
        tagName: "DataAttribute",
        name: "subVal",
        fc: "SV",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.subVal.desc",
        presCond: "MFsubst",
        type: "ClockSyncLockingKind",
        children: {
          Locked: {
            tagName: "Literal",
            name: "Locked",
            literalVal: "1",
            descID: "IEC61850_7_4.DOEnums::ClockSyncLockingKind.Locked.desc",
          },
          Unlocked10s: {
            tagName: "Literal",
            name: "Unlocked10s",
            literalVal: "2",
            descID:
              "IEC61850_7_4.DOEnums::ClockSyncLockingKind.Unlocked10s.desc",
          },
          Unlocked100s: {
            tagName: "Literal",
            name: "Unlocked100s",
            literalVal: "3",
            descID:
              "IEC61850_7_4.DOEnums::ClockSyncLockingKind.Unlocked100s.desc",
          },
          Unlocked1000s: {
            tagName: "Literal",
            name: "Unlocked1000s",
            literalVal: "4",
            descID:
              "IEC61850_7_4.DOEnums::ClockSyncLockingKind.Unlocked1000s.desc",
          },
          UnlockedMoreThan1000s: {
            tagName: "Literal",
            name: "UnlockedMoreThan1000s",
            literalVal: "5",
            descID:
              "IEC61850_7_4.DOEnums::ClockSyncLockingKind.UnlockedMoreThan1000s.desc",
          },
        },
      },
      subQ: {
        tagName: "DataAttribute",
        name: "subQ",
        fc: "SV",
        type: "Quality",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subQ.desc",
        presCond: "MFsubst",
      },
      subID: {
        tagName: "DataAttribute",
        name: "subID",
        fc: "SV",
        type: "VisString64",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subID.desc",
        presCond: "MFsubst",
      },
      blkEna: {
        tagName: "DataAttribute",
        name: "blkEna",
        fc: "BL",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.blkEna.desc",
        presCond: "O",
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  TmSrcSet1: {
    tagName: "DataObject",
    name: "TmSrcSet1",
    type: "VSG",
    descID: "IEC61850_7_4.LNGroupL::LTMS.TmSrcSet.desc",
    presCond: "Omulti",
    dsPresCond: "na",
    children: vsgChildren,
  },
  HoldTms: {
    tagName: "DataObject",
    name: "HoldTms",
    type: "ING",
    descID: "IEC61850_7_4.LNGroupL::LTMS.HoldTms.desc",
    presCond: "O",
    dsPresCond: "na",
    children: ingChildren,
  },
};
