import { asgChildren } from "./ASG.js";
import { hmvChildren } from "./HMV.js";
import { ingChildren } from "./ING.js";
import { insChildren } from "./INS.js";
import { lplChildren } from "./LPL.js";
import { mvChildren } from "./MV.js";
import { orgChildren } from "./ORG.js";
import { spcChildren } from "./SPC.js";
import { spsChildren } from "./SPS.js";
export const mhan = {
  Hz: {
    tagName: "DataObject",
    name: "Hz",
    type: "MV",
    descID: "IEC61850_7_4.AbstractLNsGroupM::HarmonicsLN.Hz.desc",
    presCond: "AllOnlyOneGroup",
    presCondArgs: "1",
    dsPresCond: "O",
    children: mvChildren,
  },
  HzSet: {
    tagName: "DataObject",
    name: "HzSet",
    type: "ASG",
    descID: "IEC61850_7_4.AbstractLNsGroupM::HarmonicsLN.HzSet.desc",
    presCond: "AllOnlyOneGroup",
    presCondArgs: "2",
    dsPresCond: "F",
    children: asgChildren,
  },
  EvTmms: {
    tagName: "DataObject",
    name: "EvTmms",
    type: "ING",
    descID: "IEC61850_7_4.AbstractLNsGroupM::HarmonicsLN.EvTmms.desc",
    presCond: "O",
    dsPresCond: "F",
    children: ingChildren,
  },
  NumCyc: {
    tagName: "DataObject",
    name: "NumCyc",
    type: "ING",
    descID: "IEC61850_7_4.AbstractLNsGroupM::HarmonicsLN.NumCyc.desc",
    presCond: "O",
    dsPresCond: "F",
    children: ingChildren,
  },
  ThdAVal: {
    tagName: "DataObject",
    name: "ThdAVal",
    type: "ASG",
    descID: "IEC61850_7_4.AbstractLNsGroupM::HarmonicsLN.ThdAVal.desc",
    presCond: "O",
    dsPresCond: "F",
    children: asgChildren,
  },
  ThdVVal: {
    tagName: "DataObject",
    name: "ThdVVal",
    type: "ASG",
    descID: "IEC61850_7_4.AbstractLNsGroupM::HarmonicsLN.ThdVVal.desc",
    presCond: "O",
    dsPresCond: "F",
    children: asgChildren,
  },
  ThdATmms: {
    tagName: "DataObject",
    name: "ThdATmms",
    type: "ING",
    descID: "IEC61850_7_4.AbstractLNsGroupM::HarmonicsLN.ThdATmms.desc",
    presCond: "O",
    dsPresCond: "F",
    children: ingChildren,
  },
  ThdVTmms: {
    tagName: "DataObject",
    name: "ThdVTmms",
    type: "ING",
    descID: "IEC61850_7_4.AbstractLNsGroupM::HarmonicsLN.ThdVTmms.desc",
    presCond: "O",
    dsPresCond: "F",
    children: ingChildren,
  },
  NomA: {
    tagName: "DataObject",
    name: "NomA",
    type: "ASG",
    descID: "IEC61850_7_4.AbstractLNsGroupM::HarmonicsLN.NomA.desc",
    presCond: "O",
    dsPresCond: "F",
    children: asgChildren,
  },
  Blk: {
    tagName: "DataObject",
    name: "Blk",
    type: "SPS",
    descID: "IEC61850_7_4.AbstractLNsCommon::FunctionLN.Blk.desc",
    presCond: "O",
    dsPresCond: "F",
    children: spsChildren,
  },
  BlkRef1: {
    tagName: "DataObject",
    name: "BlkRef1",
    type: "ORG",
    descID: "IEC61850_7_4.AbstractLNsCommon::FunctionLN.BlkRef.desc",
    presCond: "Omulti",
    dsPresCond: "F",
    children: orgChildren,
  },
  ClcExp: {
    tagName: "DataObject",
    name: "ClcExp",
    type: "SPS",
    transient: "true",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcExp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: spsChildren,
  },
  ClcNxtTmms: {
    tagName: "DataObject",
    name: "ClcNxtTmms",
    type: "INS",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcNxtTmms.desc",
    presCond: "O",
    dsPresCond: "O",
    children: insChildren,
  },
  ClcStr: {
    tagName: "DataObject",
    name: "ClcStr",
    type: "SPC",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcStr.desc",
    presCond: "O",
    dsPresCond: "O",
    children: spcChildren,
  },
  ClcMth: {
    tagName: "DataObject",
    name: "ClcMth",
    type: "ENG",
    underlyingType: "CalcMethodKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcMth.desc",
    presCond: "O",
    dsPresCond: "M",
    children: {
      setVal: {
        tagName: "DataAttribute",
        name: "setVal",
        fc: "SE",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.ENG::ENG_SE.setVal.desc",
        mandatory: true,
        presCond: "M",
        type: "CalcMethodKind",
        children: {
          UNSPECIFIED: {
            tagName: "Literal",
            name: "UNSPECIFIED",
            literalVal: "1",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.UNSPECIFIED.desc",
          },
          TRUE_RMS: {
            tagName: "Literal",
            name: "TRUE_RMS",
            literalVal: "2",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.TRUE_RMS.desc",
          },
          PEAK_FUNDAMENTAL: {
            tagName: "Literal",
            name: "PEAK_FUNDAMENTAL",
            literalVal: "3",
            descID:
              "IEC61850_7_4.DOEnums::CalcMethodKind.PEAK_FUNDAMENTAL.desc",
          },
          RMS_FUNDAMENTAL: {
            tagName: "Literal",
            name: "RMS_FUNDAMENTAL",
            literalVal: "4",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.RMS_FUNDAMENTAL.desc",
          },
          MIN: {
            tagName: "Literal",
            name: "MIN",
            literalVal: "5",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.MIN.desc",
          },
          MAX: {
            tagName: "Literal",
            name: "MAX",
            literalVal: "6",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.MAX.desc",
          },
          AVG: {
            tagName: "Literal",
            name: "AVG",
            literalVal: "7",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.AVG.desc",
          },
          SDV: {
            tagName: "Literal",
            name: "SDV",
            literalVal: "8",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.SDV.desc",
          },
          PREDICTION: {
            tagName: "Literal",
            name: "PREDICTION",
            literalVal: "9",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.PREDICTION.desc",
            deprecated: "true",
          },
          RATE: {
            tagName: "Literal",
            name: "RATE",
            literalVal: "10",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.RATE.desc",
            deprecated: "true",
          },
          "P-CLASS": {
            tagName: "Literal",
            name: "P-CLASS",
            literalVal: "11",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.P-CLASS.desc",
          },
          "M-CLASS": {
            tagName: "Literal",
            name: "M-CLASS",
            literalVal: "12",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.M-CLASS.desc",
          },
          DIFF: {
            tagName: "Literal",
            name: "DIFF",
            literalVal: "13",
            descID: "IEC61850_7_4.DOEnums::CalcMethodKind.DIFF.desc",
          },
        },
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  ClcMod: {
    tagName: "DataObject",
    name: "ClcMod",
    type: "ENG",
    underlyingType: "CalcModeKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcMod.desc",
    presCond: "O",
    dsPresCond: "O",
    children: {
      setVal: {
        tagName: "DataAttribute",
        name: "setVal",
        fc: "SE",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.ENG::ENG_SE.setVal.desc",
        mandatory: true,
        presCond: "M",
        type: "CalcModeKind",
        children: {
          TOTAL: {
            tagName: "Literal",
            name: "TOTAL",
            literalVal: "1",
            descID: "IEC61850_7_4.DOEnums::CalcModeKind.TOTAL.desc",
          },
          PERIOD: {
            tagName: "Literal",
            name: "PERIOD",
            literalVal: "2",
            descID: "IEC61850_7_4.DOEnums::CalcModeKind.PERIOD.desc",
          },
          SLIDING: {
            tagName: "Literal",
            name: "SLIDING",
            literalVal: "3",
            descID: "IEC61850_7_4.DOEnums::CalcModeKind.SLIDING.desc",
          },
        },
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  ClcIntvTyp: {
    tagName: "DataObject",
    name: "ClcIntvTyp",
    type: "ENG",
    underlyingType: "CalcIntervalKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcIntvTyp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: {
      setVal: {
        tagName: "DataAttribute",
        name: "setVal",
        fc: "SE",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.ENG::ENG_SE.setVal.desc",
        mandatory: true,
        presCond: "M",
        type: "CalcIntervalKind",
        children: {
          MS: {
            tagName: "Literal",
            name: "MS",
            literalVal: "1",
          },
          PER_CYCLE: {
            tagName: "Literal",
            name: "PER_CYCLE",
            literalVal: "2",
          },
          CYCLE: {
            tagName: "Literal",
            name: "CYCLE",
            literalVal: "3",
          },
          DAY: {
            tagName: "Literal",
            name: "DAY",
            literalVal: "4",
          },
          WEEK: {
            tagName: "Literal",
            name: "WEEK",
            literalVal: "5",
          },
          MONTH: {
            tagName: "Literal",
            name: "MONTH",
            literalVal: "6",
          },
          YEAR: {
            tagName: "Literal",
            name: "YEAR",
            literalVal: "7",
          },
          EXTERNAL: {
            tagName: "Literal",
            name: "EXTERNAL",
            literalVal: "8",
          },
        },
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  ClcIntvPer: {
    tagName: "DataObject",
    name: "ClcIntvPer",
    type: "ING",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcIntvPer.desc",
    presCond: "O",
    dsPresCond: "O",
    children: ingChildren,
  },
  NumSubIntv: {
    tagName: "DataObject",
    name: "NumSubIntv",
    type: "ING",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.NumSubIntv.desc",
    presCond: "O",
    dsPresCond: "O",
    children: ingChildren,
  },
  ClcRfTyp: {
    tagName: "DataObject",
    name: "ClcRfTyp",
    type: "ENG",
    underlyingType: "CalcIntervalKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcRfTyp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: {
      setVal: {
        tagName: "DataAttribute",
        name: "setVal",
        fc: "SE",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.ENG::ENG_SE.setVal.desc",
        mandatory: true,
        presCond: "M",
        type: "CalcIntervalKind",
        children: {
          MS: {
            tagName: "Literal",
            name: "MS",
            literalVal: "1",
          },
          PER_CYCLE: {
            tagName: "Literal",
            name: "PER_CYCLE",
            literalVal: "2",
          },
          CYCLE: {
            tagName: "Literal",
            name: "CYCLE",
            literalVal: "3",
          },
          DAY: {
            tagName: "Literal",
            name: "DAY",
            literalVal: "4",
          },
          WEEK: {
            tagName: "Literal",
            name: "WEEK",
            literalVal: "5",
          },
          MONTH: {
            tagName: "Literal",
            name: "MONTH",
            literalVal: "6",
          },
          YEAR: {
            tagName: "Literal",
            name: "YEAR",
            literalVal: "7",
          },
          EXTERNAL: {
            tagName: "Literal",
            name: "EXTERNAL",
            literalVal: "8",
          },
        },
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  ClcRfPer: {
    tagName: "DataObject",
    name: "ClcRfPer",
    type: "ING",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcRfPer.desc",
    presCond: "O",
    dsPresCond: "O",
    children: ingChildren,
  },
  ClcSrc: {
    tagName: "DataObject",
    name: "ClcSrc",
    type: "ORG",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.ClcSrc.desc",
    presCond: "F",
    dsPresCond: "M",
    children: orgChildren,
  },
  InSyn: {
    tagName: "DataObject",
    name: "InSyn",
    type: "ORG",
    descID: "IEC61850_7_4.AbstractLNsCommon::StatisticsLN.InSyn.desc",
    presCond: "O",
    dsPresCond: "O",
    children: orgChildren,
  },
  NamPlt: {
    tagName: "DataObject",
    name: "NamPlt",
    type: "LPL",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.NamPlt.desc",
    presCond: "MONamPlt",
    presCondArgsID:
      "IEC61850_7_4.AbstractLNsCommon::DomainLN__(_MONamPlt_=__((_NamPlt_))__)_.cond.AbstractLNsCommon::DomainLN.NamPlt",
    dsPresCond: "MONamPlt",
    dsPresCondArgsID:
      "IEC61850_7_4.AbstractLNsCommon::DomainLN__(_MONamPlt_=__((_NamPlt_))__)_.dsCond.AbstractLNsCommon::DomainLN.NamPlt",
    children: lplChildren,
  },
  Beh: {
    tagName: "DataObject",
    name: "Beh",
    type: "ENS",
    underlyingType: "BehaviourModeKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.Beh.desc",
    mandatory: true,
    presCond: "M",
    dsPresCond: "M",
    children: {
      stVal: {
        tagName: "DataAttribute",
        name: "stVal",
        fc: "ST",
        typeKind: "ENUMERATED",
        dchg: "true",
        dupd: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.stVal.desc",
        mandatory: true,
        presCond: "M",
        type: "BehaviourModeKind",
        children: {
          on: {
            tagName: "Literal",
            name: "on",
            literalVal: "1",
          },
          blocked: {
            tagName: "Literal",
            name: "blocked",
            literalVal: "2",
          },
          test: {
            tagName: "Literal",
            name: "test",
            literalVal: "3",
          },
          "test/blocked": {
            tagName: "Literal",
            name: "test/blocked",
            literalVal: "4",
          },
          off: {
            tagName: "Literal",
            name: "off",
            literalVal: "5",
          },
        },
      },
      q: {
        tagName: "DataAttribute",
        name: "q",
        fc: "ST",
        type: "Quality",
        qchg: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.q.desc",
        mandatory: true,
        presCond: "M",
      },
      t: {
        tagName: "DataAttribute",
        name: "t",
        fc: "ST",
        type: "Timestamp",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.t.desc",
        mandatory: true,
        presCond: "M",
      },
      subEna: {
        tagName: "DataAttribute",
        name: "subEna",
        fc: "SV",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subEna.desc",
        presCond: "MFsubst",
      },
      subVal: {
        tagName: "DataAttribute",
        name: "subVal",
        fc: "SV",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.subVal.desc",
        presCond: "MFsubst",
        type: "BehaviourModeKind",
        children: {
          on: {
            tagName: "Literal",
            name: "on",
            literalVal: "1",
          },
          blocked: {
            tagName: "Literal",
            name: "blocked",
            literalVal: "2",
          },
          test: {
            tagName: "Literal",
            name: "test",
            literalVal: "3",
          },
          "test/blocked": {
            tagName: "Literal",
            name: "test/blocked",
            literalVal: "4",
          },
          off: {
            tagName: "Literal",
            name: "off",
            literalVal: "5",
          },
        },
      },
      subQ: {
        tagName: "DataAttribute",
        name: "subQ",
        fc: "SV",
        type: "Quality",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subQ.desc",
        presCond: "MFsubst",
      },
      subID: {
        tagName: "DataAttribute",
        name: "subID",
        fc: "SV",
        type: "VisString64",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subID.desc",
        presCond: "MFsubst",
      },
      blkEna: {
        tagName: "DataAttribute",
        name: "blkEna",
        fc: "BL",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.blkEna.desc",
        presCond: "O",
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  Health: {
    tagName: "DataObject",
    name: "Health",
    type: "ENS",
    underlyingType: "HealthKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.Health.desc",
    presCond: "O",
    dsPresCond: "O",
    children: {
      stVal: {
        tagName: "DataAttribute",
        name: "stVal",
        fc: "ST",
        typeKind: "ENUMERATED",
        dchg: "true",
        dupd: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.stVal.desc",
        mandatory: true,
        presCond: "M",
        type: "HealthKind",
        children: {
          Ok: {
            tagName: "Literal",
            name: "Ok",
            literalVal: "1",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Ok.desc",
          },
          Warning: {
            tagName: "Literal",
            name: "Warning",
            literalVal: "2",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Warning.desc",
          },
          Alarm: {
            tagName: "Literal",
            name: "Alarm",
            literalVal: "3",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Alarm.desc",
          },
        },
      },
      q: {
        tagName: "DataAttribute",
        name: "q",
        fc: "ST",
        type: "Quality",
        qchg: "true",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.q.desc",
        mandatory: true,
        presCond: "M",
      },
      t: {
        tagName: "DataAttribute",
        name: "t",
        fc: "ST",
        type: "Timestamp",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.t.desc",
        mandatory: true,
        presCond: "M",
      },
      subEna: {
        tagName: "DataAttribute",
        name: "subEna",
        fc: "SV",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subEna.desc",
        presCond: "MFsubst",
      },
      subVal: {
        tagName: "DataAttribute",
        name: "subVal",
        fc: "SV",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.CDCStatusInfo::ENS.subVal.desc",
        presCond: "MFsubst",
        type: "HealthKind",
        children: {
          Ok: {
            tagName: "Literal",
            name: "Ok",
            literalVal: "1",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Ok.desc",
          },
          Warning: {
            tagName: "Literal",
            name: "Warning",
            literalVal: "2",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Warning.desc",
          },
          Alarm: {
            tagName: "Literal",
            name: "Alarm",
            literalVal: "3",
            descID: "IEC61850_7_4.DOEnums::HealthKind.Alarm.desc",
          },
        },
      },
      subQ: {
        tagName: "DataAttribute",
        name: "subQ",
        fc: "SV",
        type: "Quality",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subQ.desc",
        presCond: "MFsubst",
      },
      subID: {
        tagName: "DataAttribute",
        name: "subID",
        fc: "SV",
        type: "VisString64",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subID.desc",
        presCond: "MFsubst",
      },
      blkEna: {
        tagName: "DataAttribute",
        name: "blkEna",
        fc: "BL",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.blkEna.desc",
        presCond: "O",
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
    },
  },
  Mir: {
    tagName: "DataObject",
    name: "Mir",
    type: "SPS",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.Mir.desc",
    presCond: "MOcond",
    presCondArgs: "1",
    presCondArgsID:
      "IEC61850_7_4.AbstractLNsCommon::DomainLN__(_MOcond(1)_=__((_Mir_))__)_.cond.AbstractLNsCommon::DomainLN.Mir",
    dsPresCond: "MOcond",
    dsPresCondArgs: "1",
    dsPresCondArgsID:
      "IEC61850_7_4.AbstractLNsCommon::DomainLN__(_MOcond(1)_=__((_Mir_))__)_.dsCond.AbstractLNsCommon::DomainLN.Mir",
    children: spsChildren,
  },
  Mod: {
    tagName: "DataObject",
    name: "Mod",
    type: "ENC",
    underlyingType: "BehaviourModeKind",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.Mod.desc",
    presCond: "O",
    dsPresCond: "O",
    children: {
      origin: {
        tagName: "DataAttribute",
        name: "origin",
        fc: "ST",
        type: "Originator",
        typeKind: "CONSTRUCTED",
        descID: "IEC61850_7_3.CDCControl::ENC.origin.desc",
        presCond: "O",
        children: {
          orCat: {
            tagName: "SubDataAttribute",
            name: "orCat",
            type: "OriginatorCategoryKind",
            typeKind: "ENUMERATED",
            descID: "IEC61850_7_2.DomainTypesGeneral::S_Originator.orCat.desc",
            mandatory: true,
            presCond: "M",
            children: {
              "not-supported": {
                tagName: "Literal",
                name: "not-supported",
                literalVal: "0",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.not-supported.desc",
              },
              "bay-control": {
                tagName: "Literal",
                name: "bay-control",
                literalVal: "1",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.bay-control.desc",
              },
              "station-control": {
                tagName: "Literal",
                name: "station-control",
                literalVal: "2",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.station-control.desc",
              },
              "remote-control": {
                tagName: "Literal",
                name: "remote-control",
                literalVal: "3",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.remote-control.desc",
              },
              "automatic-bay": {
                tagName: "Literal",
                name: "automatic-bay",
                literalVal: "4",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-bay.desc",
              },
              "automatic-station": {
                tagName: "Literal",
                name: "automatic-station",
                literalVal: "5",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-station.desc",
              },
              "automatic-remote": {
                tagName: "Literal",
                name: "automatic-remote",
                literalVal: "6",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-remote.desc",
              },
              maintenance: {
                tagName: "Literal",
                name: "maintenance",
                literalVal: "7",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.maintenance.desc",
              },
              process: {
                tagName: "Literal",
                name: "process",
                literalVal: "8",
                descID:
                  "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.process.desc",
              },
            },
          },
          orIdent: {
            tagName: "SubDataAttribute",
            name: "orIdent",
            type: "Octet64",
            descID:
              "IEC61850_7_2.DomainTypesGeneral::S_Originator.orIdent.desc",
            mandatory: true,
            presCond: "M",
          },
        },
      },
      ctlNum: {
        tagName: "DataAttribute",
        name: "ctlNum",
        fc: "ST",
        type: "INT8U",
        descID: "IEC61850_7_3.CDCControl::ENC.ctlNum.desc",
        presCond: "O",
      },
      stVal: {
        tagName: "DataAttribute",
        name: "stVal",
        fc: "ST",
        typeKind: "ENUMERATED",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.stVal.desc",
        mandatory: true,
        presCond: "M",
        type: "BehaviourModeKind",
        children: {
          on: {
            tagName: "Literal",
            name: "on",
            literalVal: "1",
          },
          blocked: {
            tagName: "Literal",
            name: "blocked",
            literalVal: "2",
          },
          test: {
            tagName: "Literal",
            name: "test",
            literalVal: "3",
          },
          "test/blocked": {
            tagName: "Literal",
            name: "test/blocked",
            literalVal: "4",
          },
          off: {
            tagName: "Literal",
            name: "off",
            literalVal: "5",
          },
        },
      },
      q: {
        tagName: "DataAttribute",
        name: "q",
        fc: "ST",
        type: "Quality",
        qchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.q.desc",
        mandatory: true,
        presCond: "M",
      },
      t: {
        tagName: "DataAttribute",
        name: "t",
        fc: "ST",
        type: "Timestamp",
        descID: "IEC61850_7_3.CDCControl::ENC.t.desc",
        mandatory: true,
        presCond: "M",
      },
      stSeld: {
        tagName: "DataAttribute",
        name: "stSeld",
        fc: "ST",
        type: "BOOLEAN",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.stSeld.desc",
        presCond: "MOsbo",
      },
      opRcvd: {
        tagName: "DataAttribute",
        name: "opRcvd",
        fc: "OR",
        type: "BOOLEAN",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ControlTestingCDC.opRcvd.desc",
        presCond: "O",
      },
      opOk: {
        tagName: "DataAttribute",
        name: "opOk",
        fc: "OR",
        type: "BOOLEAN",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ControlTestingCDC.opOk.desc",
        presCond: "O",
      },
      tOpOk: {
        tagName: "DataAttribute",
        name: "tOpOk",
        fc: "OR",
        type: "Timestamp",
        descID: "IEC61850_7_3.CDCControl::ControlTestingCDC.tOpOk.desc",
        presCond: "O",
      },
      subEna: {
        tagName: "DataAttribute",
        name: "subEna",
        fc: "SV",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subEna.desc",
        presCond: "MFsubst",
      },
      subVal: {
        tagName: "DataAttribute",
        name: "subVal",
        fc: "SV",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.CDCControl::ENC.subVal.desc",
        presCond: "MFsubst",
        type: "BehaviourModeKind",
        children: {
          on: {
            tagName: "Literal",
            name: "on",
            literalVal: "1",
          },
          blocked: {
            tagName: "Literal",
            name: "blocked",
            literalVal: "2",
          },
          test: {
            tagName: "Literal",
            name: "test",
            literalVal: "3",
          },
          "test/blocked": {
            tagName: "Literal",
            name: "test/blocked",
            literalVal: "4",
          },
          off: {
            tagName: "Literal",
            name: "off",
            literalVal: "5",
          },
        },
      },
      subQ: {
        tagName: "DataAttribute",
        name: "subQ",
        fc: "SV",
        type: "Quality",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subQ.desc",
        presCond: "MFsubst",
      },
      subID: {
        tagName: "DataAttribute",
        name: "subID",
        fc: "SV",
        type: "VisString64",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subID.desc",
        presCond: "MFsubst",
      },
      blkEna: {
        tagName: "DataAttribute",
        name: "blkEna",
        fc: "BL",
        type: "BOOLEAN",
        descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.blkEna.desc",
        presCond: "O",
      },
      ctlModel: {
        tagName: "DataAttribute",
        name: "ctlModel",
        fc: "CF",
        type: "CtlModelKind",
        typeKind: "ENUMERATED",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.ctlModel.desc",
        mandatory: true,
        presCond: "M",
        children: {
          "status-only": {
            tagName: "Literal",
            name: "status-only",
            literalVal: "0",
            descID: "IEC61850_7_3.DAEnums::CtlModelKind.status-only.desc",
          },
          "direct-with-normal-security": {
            tagName: "Literal",
            name: "direct-with-normal-security",
            literalVal: "1",
            descID:
              "IEC61850_7_3.DAEnums::CtlModelKind.direct-with-normal-security.desc",
          },
          "sbo-with-normal-security": {
            tagName: "Literal",
            name: "sbo-with-normal-security",
            literalVal: "2",
            descID:
              "IEC61850_7_3.DAEnums::CtlModelKind.sbo-with-normal-security.desc",
          },
          "direct-with-enhanced-security": {
            tagName: "Literal",
            name: "direct-with-enhanced-security",
            literalVal: "3",
            descID:
              "IEC61850_7_3.DAEnums::CtlModelKind.direct-with-enhanced-security.desc",
          },
          "sbo-with-enhanced-security": {
            tagName: "Literal",
            name: "sbo-with-enhanced-security",
            literalVal: "4",
            descID:
              "IEC61850_7_3.DAEnums::CtlModelKind.sbo-with-enhanced-security.desc",
          },
        },
      },
      sboTimeout: {
        tagName: "DataAttribute",
        name: "sboTimeout",
        fc: "CF",
        type: "INT32U",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.sboTimeout.desc",
        presCond: "MOsbo",
      },
      sboClass: {
        tagName: "DataAttribute",
        name: "sboClass",
        fc: "CF",
        type: "SboClassKind",
        typeKind: "ENUMERATED",
        defaultValue: "operate-once",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.sboClass.desc",
        presCond: "O",
        children: {
          "operate-once": {
            tagName: "Literal",
            name: "operate-once",
            literalVal: "0",
            descID: "IEC61850_7_3.DAEnums::SboClassKind.operate-once.desc",
          },
          "operate-many": {
            tagName: "Literal",
            name: "operate-many",
            literalVal: "1",
            descID: "IEC61850_7_3.DAEnums::SboClassKind.operate-many.desc",
          },
        },
      },
      operTimeout: {
        tagName: "DataAttribute",
        name: "operTimeout",
        fc: "CF",
        type: "INT32U",
        dchg: "true",
        descID: "IEC61850_7_3.CDCControl::ENC.operTimeout.desc",
        presCond: "MOenhanced",
      },
      d: {
        tagName: "DataAttribute",
        name: "d",
        fc: "DC",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
        presCond: "O",
      },
      dU: {
        tagName: "DataAttribute",
        name: "dU",
        fc: "DC",
        type: "Unicode255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
        presCond: "O",
      },
      cdcName: {
        tagName: "DataAttribute",
        name: "cdcName",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
        presCond: "O",
      },
      dataNs: {
        tagName: "DataAttribute",
        name: "dataNs",
        fc: "EX",
        type: "VisString255",
        descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
        presCond: "MOdataNs",
      },
      SBO: {
        tagName: "ServiceDataAttribute",
        name: "SBO",
        typeKind: "BASIC",
        type: "VisString129",
        fc: "CO",
        presCond: "MOsboNormal",
        descID: "IEC 61850-8-1:2003.SBO",
      },
      SBOw: {
        tagName: "ServiceDataAttribute",
        name: "SBOw",
        typeKind: "CONSTRUCTED",
        type: "SBOw",
        underlyingTypeKind: "ENUMERATED",
        fc: "CO",
        presCond: "MOsboEnhanced",
        children: {
          ctlVal: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlVal",
            name: "ctlVal",
            typeKind: "undefined",
            mandatory: true,
            presCond: "M",
          },
          operTm: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.operTm",
            name: "operTm",
            typeKind: "BASIC",
            type: "Timestamp",
            presCond: "MOoperTm",
          },
          origin: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.origin",
            name: "origin",
            typeKind: "CONSTRUCTED",
            type: "Originator",
            mandatory: true,
            presCond: "M",
            children: {
              orCat: {
                tagName: "SubDataAttribute",
                name: "orCat",
                type: "OriginatorCategoryKind",
                typeKind: "ENUMERATED",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orCat.desc",
                mandatory: true,
                presCond: "M",
                children: {
                  "not-supported": {
                    tagName: "Literal",
                    name: "not-supported",
                    literalVal: "0",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.not-supported.desc",
                  },
                  "bay-control": {
                    tagName: "Literal",
                    name: "bay-control",
                    literalVal: "1",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.bay-control.desc",
                  },
                  "station-control": {
                    tagName: "Literal",
                    name: "station-control",
                    literalVal: "2",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.station-control.desc",
                  },
                  "remote-control": {
                    tagName: "Literal",
                    name: "remote-control",
                    literalVal: "3",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.remote-control.desc",
                  },
                  "automatic-bay": {
                    tagName: "Literal",
                    name: "automatic-bay",
                    literalVal: "4",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-bay.desc",
                  },
                  "automatic-station": {
                    tagName: "Literal",
                    name: "automatic-station",
                    literalVal: "5",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-station.desc",
                  },
                  "automatic-remote": {
                    tagName: "Literal",
                    name: "automatic-remote",
                    literalVal: "6",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-remote.desc",
                  },
                  maintenance: {
                    tagName: "Literal",
                    name: "maintenance",
                    literalVal: "7",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.maintenance.desc",
                  },
                  process: {
                    tagName: "Literal",
                    name: "process",
                    literalVal: "8",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.process.desc",
                  },
                },
              },
              orIdent: {
                tagName: "SubDataAttribute",
                name: "orIdent",
                type: "Octet64",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orIdent.desc",
                mandatory: true,
                presCond: "M",
              },
            },
          },
          ctlNum: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlNum",
            name: "ctlNum",
            typeKind: "BASIC",
            type: "INT8U",
            mandatory: true,
            presCond: "M",
          },
          T: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.T",
            name: "T",
            typeKind: "BASIC",
            type: "Timestamp",
            mandatory: true,
            presCond: "M",
          },
          Test: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.Test",
            name: "Test",
            typeKind: "BASIC",
            type: "BOOLEAN",
            mandatory: true,
            presCond: "M",
          },
          Check: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.Check",
            name: "Check",
            typeKind: "BASIC",
            type: "Check",
            mandatory: true,
            presCond: "M",
          },
        },
      },
      Oper: {
        tagName: "ServiceDataAttribute",
        name: "Oper",
        typeKind: "CONSTRUCTED",
        type: "Oper",
        underlyingTypeKind: "ENUMERATED",
        fc: "CO",
        presCond: "MOctrl",
        children: {
          ctlVal: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlVal",
            name: "ctlVal",
            typeKind: "undefined",
            mandatory: true,
            presCond: "M",
          },
          operTm: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.operTm",
            name: "operTm",
            typeKind: "BASIC",
            type: "Timestamp",
            presCond: "MOoperTm",
          },
          origin: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.origin",
            name: "origin",
            typeKind: "CONSTRUCTED",
            type: "Originator",
            mandatory: true,
            presCond: "M",
            children: {
              orCat: {
                tagName: "SubDataAttribute",
                name: "orCat",
                type: "OriginatorCategoryKind",
                typeKind: "ENUMERATED",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orCat.desc",
                mandatory: true,
                presCond: "M",
                children: {
                  "not-supported": {
                    tagName: "Literal",
                    name: "not-supported",
                    literalVal: "0",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.not-supported.desc",
                  },
                  "bay-control": {
                    tagName: "Literal",
                    name: "bay-control",
                    literalVal: "1",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.bay-control.desc",
                  },
                  "station-control": {
                    tagName: "Literal",
                    name: "station-control",
                    literalVal: "2",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.station-control.desc",
                  },
                  "remote-control": {
                    tagName: "Literal",
                    name: "remote-control",
                    literalVal: "3",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.remote-control.desc",
                  },
                  "automatic-bay": {
                    tagName: "Literal",
                    name: "automatic-bay",
                    literalVal: "4",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-bay.desc",
                  },
                  "automatic-station": {
                    tagName: "Literal",
                    name: "automatic-station",
                    literalVal: "5",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-station.desc",
                  },
                  "automatic-remote": {
                    tagName: "Literal",
                    name: "automatic-remote",
                    literalVal: "6",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-remote.desc",
                  },
                  maintenance: {
                    tagName: "Literal",
                    name: "maintenance",
                    literalVal: "7",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.maintenance.desc",
                  },
                  process: {
                    tagName: "Literal",
                    name: "process",
                    literalVal: "8",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.process.desc",
                  },
                },
              },
              orIdent: {
                tagName: "SubDataAttribute",
                name: "orIdent",
                type: "Octet64",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orIdent.desc",
                mandatory: true,
                presCond: "M",
              },
            },
          },
          ctlNum: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlNum",
            name: "ctlNum",
            typeKind: "BASIC",
            type: "INT8U",
            mandatory: true,
            presCond: "M",
          },
          T: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.T",
            name: "T",
            typeKind: "BASIC",
            type: "Timestamp",
            mandatory: true,
            presCond: "M",
          },
          Test: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.Test",
            name: "Test",
            typeKind: "BASIC",
            type: "BOOLEAN",
            mandatory: true,
            presCond: "M",
          },
          Check: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.Check",
            name: "Check",
            typeKind: "BASIC",
            type: "Check",
            mandatory: true,
            presCond: "M",
          },
        },
      },
      Cancel: {
        tagName: "ServiceDataAttribute",
        name: "Cancel",
        typeKind: "CONSTRUCTED",
        type: "Cancel",
        underlyingTypeKind: "ENUMERATED",
        fc: "CO",
        presCond: "MOsbo",
        children: {
          ctlVal: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlVal",
            name: "ctlVal",
            typeKind: "undefined",
            mandatory: true,
            presCond: "M",
          },
          operTm: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.operTm",
            name: "operTm",
            typeKind: "BASIC",
            type: "Timestamp",
            presCond: "MOoperTm",
          },
          origin: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.origin",
            name: "origin",
            typeKind: "CONSTRUCTED",
            type: "Originator",
            mandatory: true,
            presCond: "M",
            children: {
              orCat: {
                tagName: "SubDataAttribute",
                name: "orCat",
                type: "OriginatorCategoryKind",
                typeKind: "ENUMERATED",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orCat.desc",
                mandatory: true,
                presCond: "M",
                children: {
                  "not-supported": {
                    tagName: "Literal",
                    name: "not-supported",
                    literalVal: "0",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.not-supported.desc",
                  },
                  "bay-control": {
                    tagName: "Literal",
                    name: "bay-control",
                    literalVal: "1",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.bay-control.desc",
                  },
                  "station-control": {
                    tagName: "Literal",
                    name: "station-control",
                    literalVal: "2",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.station-control.desc",
                  },
                  "remote-control": {
                    tagName: "Literal",
                    name: "remote-control",
                    literalVal: "3",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.remote-control.desc",
                  },
                  "automatic-bay": {
                    tagName: "Literal",
                    name: "automatic-bay",
                    literalVal: "4",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-bay.desc",
                  },
                  "automatic-station": {
                    tagName: "Literal",
                    name: "automatic-station",
                    literalVal: "5",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-station.desc",
                  },
                  "automatic-remote": {
                    tagName: "Literal",
                    name: "automatic-remote",
                    literalVal: "6",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.automatic-remote.desc",
                  },
                  maintenance: {
                    tagName: "Literal",
                    name: "maintenance",
                    literalVal: "7",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.maintenance.desc",
                  },
                  process: {
                    tagName: "Literal",
                    name: "process",
                    literalVal: "8",
                    descID:
                      "IEC61850_7_2.DomainTypesEnums::OriginatorCategoryKind.process.desc",
                  },
                },
              },
              orIdent: {
                tagName: "SubDataAttribute",
                name: "orIdent",
                type: "Octet64",
                descID:
                  "IEC61850_7_2.DomainTypesGeneral::S_Originator.orIdent.desc",
                mandatory: true,
                presCond: "M",
              },
            },
          },
          ctlNum: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.ctlNum",
            name: "ctlNum",
            typeKind: "BASIC",
            type: "INT8U",
            mandatory: true,
            presCond: "M",
          },
          T: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.T",
            name: "T",
            typeKind: "BASIC",
            type: "Timestamp",
            mandatory: true,
            presCond: "M",
          },
          Test: {
            tagName: "SubDataAttribute",
            descID: "IEC 61850-8-1:2003.Test",
            name: "Test",
            typeKind: "BASIC",
            type: "BOOLEAN",
            mandatory: true,
            presCond: "M",
          },
        },
      },
    },
  },
  InRef1: {
    tagName: "DataObject",
    name: "InRef1",
    type: "ORG",
    descID: "IEC61850_7_4.AbstractLNsCommon::DomainLN.InRef.desc",
    presCond: "Omulti",
    dsPresCond: "Omulti",
    children: orgChildren,
  },
  HaAmp: {
    tagName: "DataObject",
    name: "HaAmp",
    type: "HMV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.HaAmp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: hmvChildren,
  },
  HaVol: {
    tagName: "DataObject",
    name: "HaVol",
    type: "HMV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.HaVol.desc",
    presCond: "O",
    dsPresCond: "O",
    children: hmvChildren,
  },
  HaWatt: {
    tagName: "DataObject",
    name: "HaWatt",
    type: "HMV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.HaWatt.desc",
    presCond: "O",
    dsPresCond: "O",
    children: hmvChildren,
  },
  HaVolAmpr: {
    tagName: "DataObject",
    name: "HaVolAmpr",
    type: "HMV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.HaVolAmpr.desc",
    presCond: "O",
    dsPresCond: "O",
    children: hmvChildren,
  },
  HaVolAmp: {
    tagName: "DataObject",
    name: "HaVolAmp",
    type: "HMV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.HaVolAmp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: hmvChildren,
  },
  HaRmsAmp: {
    tagName: "DataObject",
    name: "HaRmsAmp",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.HaRmsAmp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  HaRmsVol: {
    tagName: "DataObject",
    name: "HaRmsVol",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.HaRmsVol.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  HaTuWatt: {
    tagName: "DataObject",
    name: "HaTuWatt",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.HaTuWatt.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  HaTsWatt: {
    tagName: "DataObject",
    name: "HaTsWatt",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.HaTsWatt.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  HaAmpTm: {
    tagName: "DataObject",
    name: "HaAmpTm",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.HaAmpTm.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  HaKFact: {
    tagName: "DataObject",
    name: "HaKFact",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.HaKFact.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  HaTdFact: {
    tagName: "DataObject",
    name: "HaTdFact",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.HaTdFact.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  ThdAmp: {
    tagName: "DataObject",
    name: "ThdAmp",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.ThdAmp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  ThdOddAmp: {
    tagName: "DataObject",
    name: "ThdOddAmp",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.ThdOddAmp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  ThdEvnAmp: {
    tagName: "DataObject",
    name: "ThdEvnAmp",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.ThdEvnAmp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  TddAmp: {
    tagName: "DataObject",
    name: "TddAmp",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.TddAmp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  TddOddAmp: {
    tagName: "DataObject",
    name: "TddOddAmp",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.TddOddAmp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  TddEvnAmp: {
    tagName: "DataObject",
    name: "TddEvnAmp",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.TddEvnAmp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  ThdVol: {
    tagName: "DataObject",
    name: "ThdVol",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.ThdVol.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  ThdOddVol: {
    tagName: "DataObject",
    name: "ThdOddVol",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.ThdOddVol.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  ThdEvnVol: {
    tagName: "DataObject",
    name: "ThdEvnVol",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.ThdEvnVol.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  HaCfAmp: {
    tagName: "DataObject",
    name: "HaCfAmp",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.HaCfAmp.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  HaCfVol: {
    tagName: "DataObject",
    name: "HaCfVol",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.HaCfVol.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
  HaTiFact: {
    tagName: "DataObject",
    name: "HaTiFact",
    type: "MV",
    descID: "IEC61850_7_4.LNGroupM::MHAN.HaTiFact.desc",
    presCond: "O",
    dsPresCond: "O",
    children: mvChildren,
  },
};
