export const orgChildren = {
  setSrcRef: {
    tagName: "DataAttribute",
    name: "setSrcRef",
    fc: "SP",
    type: "ObjRef",
    dchg: "true",
    descID: "IEC61850_7_3.ORG::ORG.setSrcRef.desc",
    mandatory: true,
    presCond: "M",
  },
  setTstRef: {
    tagName: "DataAttribute",
    name: "setTstRef",
    fc: "SP",
    type: "ObjRef",
    dchg: "true",
    descID: "IEC61850_7_3.ORG::ORG.setTstRef.desc",
    presCond: "AllOrNonePerGroup",
    presCondArgs: "1",
  },
  setSrcCB: {
    tagName: "DataAttribute",
    name: "setSrcCB",
    fc: "SP",
    type: "ObjRef",
    dchg: "true",
    descID: "IEC61850_7_3.ORG::ORG.setSrcCB.desc",
    presCond: "O",
  },
  setTstCB: {
    tagName: "DataAttribute",
    name: "setTstCB",
    fc: "SP",
    type: "ObjRef",
    dchg: "true",
    descID: "IEC61850_7_3.ORG::ORG.setTstCB.desc",
    presCond: "OF",
    presCondArgs: "setTstRef",
  },
  intAddr: {
    tagName: "DataAttribute",
    name: "intAddr",
    fc: "SP",
    type: "VisString255",
    dchg: "true",
    descID: "IEC61850_7_3.ORG::ORG.intAddr.desc",
    presCond: "O",
  },
  tstEna: {
    tagName: "DataAttribute",
    name: "tstEna",
    fc: "SP",
    type: "BOOLEAN",
    dchg: "true",
    descID: "IEC61850_7_3.ORG::ORG.tstEna.desc",
    presCond: "AllOrNonePerGroup",
    presCondArgs: "1",
  },
  purpose: {
    tagName: "DataAttribute",
    name: "purpose",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.ORG::ORG.purpose.desc",
    presCond: "O",
  },
  d: {
    tagName: "DataAttribute",
    name: "d",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
    presCond: "O",
  },
  dU: {
    tagName: "DataAttribute",
    name: "dU",
    fc: "DC",
    type: "Unicode255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
    presCond: "O",
  },
  cdcName: {
    tagName: "DataAttribute",
    name: "cdcName",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
    presCond: "O",
  },
  dataNs: {
    tagName: "DataAttribute",
    name: "dataNs",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
    presCond: "MOdataNs",
  },
};
