export const spsChildren = {
  stVal: {
    tagName: "DataAttribute",
    name: "stVal",
    fc: "ST",
    type: "BOOLEAN",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::SPS.stVal.desc",
    mandatory: true,
    presCond: "M",
  },
  q: {
    tagName: "DataAttribute",
    name: "q",
    fc: "ST",
    type: "Quality",
    qchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::SPS.q.desc",
    mandatory: true,
    presCond: "M",
  },
  t: {
    tagName: "DataAttribute",
    name: "t",
    fc: "ST",
    type: "Timestamp",
    descID: "IEC61850_7_3.CDCStatusInfo::SPS.t.desc",
    mandatory: true,
    presCond: "M",
  },
  subEna: {
    tagName: "DataAttribute",
    name: "subEna",
    fc: "SV",
    type: "BOOLEAN",
    descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subEna.desc",
    presCond: "MFsubst",
  },
  subVal: {
    tagName: "DataAttribute",
    name: "subVal",
    fc: "SV",
    type: "BOOLEAN",
    descID: "IEC61850_7_3.CDCStatusInfo::SPS.subVal.desc",
    presCond: "MFsubst",
  },
  subQ: {
    tagName: "DataAttribute",
    name: "subQ",
    fc: "SV",
    type: "Quality",
    descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subQ.desc",
    presCond: "MFsubst",
  },
  subID: {
    tagName: "DataAttribute",
    name: "subID",
    fc: "SV",
    type: "VisString64",
    descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subID.desc",
    presCond: "MFsubst",
  },
  blkEna: {
    tagName: "DataAttribute",
    name: "blkEna",
    fc: "BL",
    type: "BOOLEAN",
    descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.blkEna.desc",
    presCond: "O",
  },
  d: {
    tagName: "DataAttribute",
    name: "d",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
    presCond: "O",
  },
  dU: {
    tagName: "DataAttribute",
    name: "dU",
    fc: "DC",
    type: "Unicode255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
    presCond: "O",
  },
  cdcName: {
    tagName: "DataAttribute",
    name: "cdcName",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
    presCond: "O",
  },
  dataNs: {
    tagName: "DataAttribute",
    name: "dataNs",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
    presCond: "MOdataNs",
  },
};

export const sps = {
  tagName: "DataObject",
  name: "Loc",
  type: "SPS",
  descID: "IEC61850_7_4.AbstractLNsCommon::ControllingLN.Loc.desc",
  presCond: "O",
  dsPresCond: "F",
  children: {
    stVal: {
      tagName: "DataAttribute",
      name: "stVal",
      fc: "ST",
      type: "BOOLEAN",
      dchg: "true",
      descID: "IEC61850_7_3.CDCStatusInfo::SPS.stVal.desc",
      mandatory: true,
      presCond: "M",
    },
    q: {
      tagName: "DataAttribute",
      name: "q",
      fc: "ST",
      type: "Quality",
      qchg: "true",
      descID: "IEC61850_7_3.CDCStatusInfo::SPS.q.desc",
      mandatory: true,
      presCond: "M",
    },
    t: {
      tagName: "DataAttribute",
      name: "t",
      fc: "ST",
      type: "Timestamp",
      descID: "IEC61850_7_3.CDCStatusInfo::SPS.t.desc",
      mandatory: true,
      presCond: "M",
    },
    subEna: {
      tagName: "DataAttribute",
      name: "subEna",
      fc: "SV",
      type: "BOOLEAN",
      descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subEna.desc",
      presCond: "MFsubst",
    },
    subVal: {
      tagName: "DataAttribute",
      name: "subVal",
      fc: "SV",
      type: "BOOLEAN",
      descID: "IEC61850_7_3.CDCStatusInfo::SPS.subVal.desc",
      presCond: "MFsubst",
    },
    subQ: {
      tagName: "DataAttribute",
      name: "subQ",
      fc: "SV",
      type: "Quality",
      descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subQ.desc",
      presCond: "MFsubst",
    },
    subID: {
      tagName: "DataAttribute",
      name: "subID",
      fc: "SV",
      type: "VisString64",
      descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.subID.desc",
      presCond: "MFsubst",
    },
    blkEna: {
      tagName: "DataAttribute",
      name: "blkEna",
      fc: "BL",
      type: "BOOLEAN",
      descID: "IEC61850_7_3.CoreAbstractCDCs::SubstitutionCDC.blkEna.desc",
      presCond: "O",
    },
    d: {
      tagName: "DataAttribute",
      name: "d",
      fc: "DC",
      type: "VisString255",
      descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
      presCond: "O",
    },
    dU: {
      tagName: "DataAttribute",
      name: "dU",
      fc: "DC",
      type: "Unicode255",
      descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
      presCond: "O",
    },
    cdcName: {
      tagName: "DataAttribute",
      name: "cdcName",
      fc: "EX",
      type: "VisString255",
      descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
      presCond: "O",
    },
    dataNs: {
      tagName: "DataAttribute",
      name: "dataNs",
      fc: "EX",
      type: "VisString255",
      descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
      presCond: "MOdataNs",
    },
  },
};
