export const tsgChildren = {
  setTm: {
    tagName: "DataAttribute",
    name: "setTm",
    fc: "SE",
    type: "Timestamp",
    descID: "IEC61850_7_3.TSG::TSG_SE.setTm.desc",
    presCond: "AtLeastOne",
    presCondArgs: "1",
  },
  setCal: {
    tagName: "DataAttribute",
    name: "setCal",
    fc: "SE",
    type: "CalendarTime",
    typeKind: "CONSTRUCTED",
    descID: "IEC61850_7_3.TSG::TSG_SE.setCal.desc",
    presCond: "AtLeastOne",
    presCondArgs: "1",
    children: {
      occ: {
        tagName: "SubDataAttribute",
        name: "occ",
        type: "INT16U",
        descID: "IEC61850_7_3.ConstructedDAs::CalendarTime.occ.desc",
        mandatory: true,
        presCond: "M",
      },
      occType: {
        tagName: "SubDataAttribute",
        name: "occType",
        type: "OccurrenceKind",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.ConstructedDAs::CalendarTime.occType.desc",
        mandatory: true,
        presCond: "M",
        children: {
          Time: {
            tagName: "Literal",
            name: "Time",
            literalVal: "0",
          },
          WeekDay: {
            tagName: "Literal",
            name: "WeekDay",
            literalVal: "1",
          },
          WeekOfYear: {
            tagName: "Literal",
            name: "WeekOfYear",
            literalVal: "2",
          },
          DayOfMonth: {
            tagName: "Literal",
            name: "DayOfMonth",
            literalVal: "3",
          },
          DayOfYear: {
            tagName: "Literal",
            name: "DayOfYear",
            literalVal: "4",
          },
          NONE: {
            tagName: "Literal",
            name: "NONE",
            literalVal: "5",
            descID: "IEC61850_7_3.DAEnums::OccurrenceKind.NONE.desc",
          },
        },
      },
      occPer: {
        tagName: "SubDataAttribute",
        name: "occPer",
        type: "PeriodKind",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.ConstructedDAs::CalendarTime.occPer.desc",
        mandatory: true,
        presCond: "M",
        children: {
          Hour: {
            tagName: "Literal",
            name: "Hour",
            literalVal: "0",
          },
          Day: {
            tagName: "Literal",
            name: "Day",
            literalVal: "1",
          },
          Week: {
            tagName: "Literal",
            name: "Week",
            literalVal: "2",
          },
          Month: {
            tagName: "Literal",
            name: "Month",
            literalVal: "3",
          },
          Year: {
            tagName: "Literal",
            name: "Year",
            literalVal: "4",
          },
        },
      },
      weekDay: {
        tagName: "SubDataAttribute",
        name: "weekDay",
        type: "WeekdayKind",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.ConstructedDAs::CalendarTime.weekDay.desc",
        mandatory: true,
        presCond: "M",
        children: {
          reserved: {
            tagName: "Literal",
            name: "reserved",
            literalVal: "0",
          },
          Monday: {
            tagName: "Literal",
            name: "Monday",
            literalVal: "1",
          },
          Tuesday: {
            tagName: "Literal",
            name: "Tuesday",
            literalVal: "2",
          },
          Wednesday: {
            tagName: "Literal",
            name: "Wednesday",
            literalVal: "3",
          },
          Thursday: {
            tagName: "Literal",
            name: "Thursday",
            literalVal: "4",
          },
          Friday: {
            tagName: "Literal",
            name: "Friday",
            literalVal: "5",
          },
          Saturday: {
            tagName: "Literal",
            name: "Saturday",
            literalVal: "6",
          },
          Sunday: {
            tagName: "Literal",
            name: "Sunday",
            literalVal: "7",
          },
        },
      },
      month: {
        tagName: "SubDataAttribute",
        name: "month",
        type: "MonthKind",
        typeKind: "ENUMERATED",
        descID: "IEC61850_7_3.ConstructedDAs::CalendarTime.month.desc",
        mandatory: true,
        presCond: "M",
        children: {
          reserved: {
            tagName: "Literal",
            name: "reserved",
            literalVal: "0",
          },
          January: {
            tagName: "Literal",
            name: "January",
            literalVal: "1",
          },
          February: {
            tagName: "Literal",
            name: "February",
            literalVal: "2",
          },
          March: {
            tagName: "Literal",
            name: "March",
            literalVal: "3",
          },
          April: {
            tagName: "Literal",
            name: "April",
            literalVal: "4",
          },
          May: {
            tagName: "Literal",
            name: "May",
            literalVal: "5",
          },
          June: {
            tagName: "Literal",
            name: "June",
            literalVal: "6",
          },
          July: {
            tagName: "Literal",
            name: "July",
            literalVal: "7",
          },
          August: {
            tagName: "Literal",
            name: "August",
            literalVal: "8",
          },
          September: {
            tagName: "Literal",
            name: "September",
            literalVal: "9",
          },
          October: {
            tagName: "Literal",
            name: "October",
            literalVal: "10",
          },
          November: {
            tagName: "Literal",
            name: "November",
            literalVal: "11",
          },
          December: {
            tagName: "Literal",
            name: "December",
            literalVal: "12",
          },
        },
      },
      day: {
        tagName: "SubDataAttribute",
        name: "day",
        type: "INT8U",
        minValue: "1",
        maxValue: "31",
        descID: "IEC61850_7_3.ConstructedDAs::CalendarTime.day.desc",
        mandatory: true,
        presCond: "M",
      },
      hr: {
        tagName: "SubDataAttribute",
        name: "hr",
        type: "INT8U",
        minValue: "0",
        maxValue: "23",
        descID: "IEC61850_7_3.ConstructedDAs::CalendarTime.hr.desc",
        mandatory: true,
        presCond: "M",
      },
      mn: {
        tagName: "SubDataAttribute",
        name: "mn",
        type: "INT8U",
        minValue: "0",
        maxValue: "59",
        descID: "IEC61850_7_3.ConstructedDAs::CalendarTime.mn.desc",
        mandatory: true,
        presCond: "M",
      },
    },
  },
  d: {
    tagName: "DataAttribute",
    name: "d",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
    presCond: "O",
  },
  dU: {
    tagName: "DataAttribute",
    name: "dU",
    fc: "DC",
    type: "Unicode255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
    presCond: "O",
  },
  cdcName: {
    tagName: "DataAttribute",
    name: "cdcName",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
    presCond: "O",
  },
  dataNs: {
    tagName: "DataAttribute",
    name: "dataNs",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
    presCond: "MOdataNs",
  },
};
