export const vssChildren = {
  stVal: {
    tagName: "DataAttribute",
    name: "stVal",
    fc: "ST",
    type: "VisString255",
    dchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::VSS.stVal.desc",
    mandatory: true,
    presCond: "M",
  },
  q: {
    tagName: "DataAttribute",
    name: "q",
    fc: "ST",
    type: "Quality",
    qchg: "true",
    descID: "IEC61850_7_3.CDCStatusInfo::VSS.q.desc",
    mandatory: true,
    presCond: "M",
  },
  t: {
    tagName: "DataAttribute",
    name: "t",
    fc: "ST",
    type: "Timestamp",
    descID: "IEC61850_7_3.CDCStatusInfo::VSS.t.desc",
    mandatory: true,
    presCond: "M",
  },
  d: {
    tagName: "DataAttribute",
    name: "d",
    fc: "DC",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.d.desc",
    presCond: "O",
  },
  dU: {
    tagName: "DataAttribute",
    name: "dU",
    fc: "DC",
    type: "Unicode255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dU.desc",
    presCond: "O",
  },
  cdcName: {
    tagName: "DataAttribute",
    name: "cdcName",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.cdcName.desc",
    presCond: "O",
  },
  dataNs: {
    tagName: "DataAttribute",
    name: "dataNs",
    fc: "EX",
    type: "VisString255",
    descID: "IEC61850_7_3.CoreAbstractCDCs::BasePrimitiveCDC.dataNs.desc",
    presCond: "MOdataNs",
  },
};
